/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Aircraft resource object
 * @export
 * @interface Aircraft
 */
export interface Aircraft {
    /**
     * 
     * @type {number}
     * @memberof Aircraft
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Aircraft
     */
    name: string;
}

/**
 * Check if a given object implements the Aircraft interface.
 */
export function instanceOfAircraft(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function AircraftFromJSON(json: any): Aircraft {
    return AircraftFromJSONTyped(json, false);
}

export function AircraftFromJSONTyped(json: any, ignoreDiscriminator: boolean): Aircraft {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function AircraftToJSON(value?: Aircraft | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}

