/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Request for attaching survey type to a model.
 *            `model_id` and `survey_type_id` combination must be unique
 *            within the `model.model_survey_type` table.
 * @export
 * @interface AttachSurveyTypeToModelRequest
 */
export interface AttachSurveyTypeToModelRequest {
    /**
     * 
     * @type {number}
     * @memberof AttachSurveyTypeToModelRequest
     */
    modelId: number;
    /**
     * 
     * @type {number}
     * @memberof AttachSurveyTypeToModelRequest
     */
    surveyTypeId: number;
}

/**
 * Check if a given object implements the AttachSurveyTypeToModelRequest interface.
 */
export function instanceOfAttachSurveyTypeToModelRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "modelId" in value;
    isInstance = isInstance && "surveyTypeId" in value;

    return isInstance;
}

export function AttachSurveyTypeToModelRequestFromJSON(json: any): AttachSurveyTypeToModelRequest {
    return AttachSurveyTypeToModelRequestFromJSONTyped(json, false);
}

export function AttachSurveyTypeToModelRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttachSurveyTypeToModelRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'modelId': json['model_id'],
        'surveyTypeId': json['survey_type_id'],
    };
}

export function AttachSurveyTypeToModelRequestToJSON(value?: AttachSurveyTypeToModelRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'model_id': value.modelId,
        'survey_type_id': value.surveyTypeId,
    };
}

