/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Request for detaching model from an aerial survey.
 *            `model_id` and `aerial_survey_id` combination must exist
 *            in the `model.model_aerial_survey` table.
 * @export
 * @interface DetachModelFromAerialSurveyRequest
 */
export interface DetachModelFromAerialSurveyRequest {
    /**
     * 
     * @type {number}
     * @memberof DetachModelFromAerialSurveyRequest
     */
    modelId: number;
    /**
     * 
     * @type {number}
     * @memberof DetachModelFromAerialSurveyRequest
     */
    aerialSurveyId: number;
}

/**
 * Check if a given object implements the DetachModelFromAerialSurveyRequest interface.
 */
export function instanceOfDetachModelFromAerialSurveyRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "modelId" in value;
    isInstance = isInstance && "aerialSurveyId" in value;

    return isInstance;
}

export function DetachModelFromAerialSurveyRequestFromJSON(json: any): DetachModelFromAerialSurveyRequest {
    return DetachModelFromAerialSurveyRequestFromJSONTyped(json, false);
}

export function DetachModelFromAerialSurveyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetachModelFromAerialSurveyRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'modelId': json['model_id'],
        'aerialSurveyId': json['aerial_survey_id'],
    };
}

export function DetachModelFromAerialSurveyRequestToJSON(value?: DetachModelFromAerialSurveyRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'model_id': value.modelId,
        'aerial_survey_id': value.aerialSurveyId,
    };
}

