/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EntryColumnMapping } from './EntryColumnMapping';
import {
    EntryColumnMappingFromJSON,
    EntryColumnMappingFromJSONTyped,
    EntryColumnMappingToJSON,
} from './EntryColumnMapping';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
} from './PaginationMeta';

/**
 * Index entry column mappings response object.
 * @export
 * @interface IndexEntryColumnMappingsResponse
 */
export interface IndexEntryColumnMappingsResponse {
    /**
     * 
     * @type {Array<EntryColumnMapping>}
     * @memberof IndexEntryColumnMappingsResponse
     */
    data: Array<EntryColumnMapping>;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof IndexEntryColumnMappingsResponse
     */
    meta: PaginationMeta;
    /**
     * 
     * @type {string}
     * @memberof IndexEntryColumnMappingsResponse
     */
    message: string;
}

/**
 * Check if a given object implements the IndexEntryColumnMappingsResponse interface.
 */
export function instanceOfIndexEntryColumnMappingsResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "meta" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function IndexEntryColumnMappingsResponseFromJSON(json: any): IndexEntryColumnMappingsResponse {
    return IndexEntryColumnMappingsResponseFromJSONTyped(json, false);
}

export function IndexEntryColumnMappingsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndexEntryColumnMappingsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(EntryColumnMappingFromJSON)),
        'meta': PaginationMetaFromJSON(json['meta']),
        'message': json['message'],
    };
}

export function IndexEntryColumnMappingsResponseToJSON(value?: IndexEntryColumnMappingsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(EntryColumnMappingToJSON)),
        'meta': PaginationMetaToJSON(value.meta),
        'message': value.message,
    };
}

