/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ColumnMapping } from './ColumnMapping';
import {
    ColumnMappingFromJSON,
    ColumnMappingFromJSONTyped,
    ColumnMappingToJSON,
} from './ColumnMapping';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
} from './PaginationMeta';

/**
 * Index column mappings response object.
 * @export
 * @interface IndexColumnMappingsResponse
 */
export interface IndexColumnMappingsResponse {
    /**
     * 
     * @type {Array<ColumnMapping>}
     * @memberof IndexColumnMappingsResponse
     */
    data: Array<ColumnMapping>;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof IndexColumnMappingsResponse
     */
    meta: PaginationMeta;
    /**
     * 
     * @type {string}
     * @memberof IndexColumnMappingsResponse
     */
    message: string;
}

/**
 * Check if a given object implements the IndexColumnMappingsResponse interface.
 */
export function instanceOfIndexColumnMappingsResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "meta" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function IndexColumnMappingsResponseFromJSON(json: any): IndexColumnMappingsResponse {
    return IndexColumnMappingsResponseFromJSONTyped(json, false);
}

export function IndexColumnMappingsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndexColumnMappingsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ColumnMappingFromJSON)),
        'meta': PaginationMetaFromJSON(json['meta']),
        'message': json['message'],
    };
}

export function IndexColumnMappingsResponseToJSON(value?: IndexColumnMappingsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(ColumnMappingToJSON)),
        'meta': PaginationMetaToJSON(value.meta),
        'message': value.message,
    };
}

