/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BetaVar } from './BetaVar';
import {
    BetaVarFromJSON,
    BetaVarFromJSONTyped,
    BetaVarToJSON,
} from './BetaVar';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
} from './PaginationMeta';

/**
 * Index beta vars response object.
 * @export
 * @interface IndexBetaVarsResponse
 */
export interface IndexBetaVarsResponse {
    /**
     * 
     * @type {Array<BetaVar>}
     * @memberof IndexBetaVarsResponse
     */
    data: Array<BetaVar>;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof IndexBetaVarsResponse
     */
    meta: PaginationMeta;
    /**
     * 
     * @type {string}
     * @memberof IndexBetaVarsResponse
     */
    message: string;
}

/**
 * Check if a given object implements the IndexBetaVarsResponse interface.
 */
export function instanceOfIndexBetaVarsResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "meta" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function IndexBetaVarsResponseFromJSON(json: any): IndexBetaVarsResponse {
    return IndexBetaVarsResponseFromJSONTyped(json, false);
}

export function IndexBetaVarsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndexBetaVarsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(BetaVarFromJSON)),
        'meta': PaginationMetaFromJSON(json['meta']),
        'message': json['message'],
    };
}

export function IndexBetaVarsResponseToJSON(value?: IndexBetaVarsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(BetaVarToJSON)),
        'meta': PaginationMetaToJSON(value.meta),
        'message': value.message,
    };
}

