/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AerialSurveyEntryWithDesign } from './AerialSurveyEntryWithDesign';
import {
    AerialSurveyEntryWithDesignFromJSON,
    AerialSurveyEntryWithDesignFromJSONTyped,
    AerialSurveyEntryWithDesignToJSON,
} from './AerialSurveyEntryWithDesign';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
} from './PaginationMeta';

/**
 * Index aerial survey entries with designs response object.
 * @export
 * @interface IndexAerialSurveyEntriesWithDesignsResponse
 */
export interface IndexAerialSurveyEntriesWithDesignsResponse {
    /**
     * 
     * @type {Array<AerialSurveyEntryWithDesign>}
     * @memberof IndexAerialSurveyEntriesWithDesignsResponse
     */
    data: Array<AerialSurveyEntryWithDesign>;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof IndexAerialSurveyEntriesWithDesignsResponse
     */
    meta: PaginationMeta;
    /**
     * 
     * @type {string}
     * @memberof IndexAerialSurveyEntriesWithDesignsResponse
     */
    message: string;
}

/**
 * Check if a given object implements the IndexAerialSurveyEntriesWithDesignsResponse interface.
 */
export function instanceOfIndexAerialSurveyEntriesWithDesignsResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "meta" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function IndexAerialSurveyEntriesWithDesignsResponseFromJSON(json: any): IndexAerialSurveyEntriesWithDesignsResponse {
    return IndexAerialSurveyEntriesWithDesignsResponseFromJSONTyped(json, false);
}

export function IndexAerialSurveyEntriesWithDesignsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndexAerialSurveyEntriesWithDesignsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(AerialSurveyEntryWithDesignFromJSON)),
        'meta': PaginationMetaFromJSON(json['meta']),
        'message': json['message'],
    };
}

export function IndexAerialSurveyEntriesWithDesignsResponseToJSON(value?: IndexAerialSurveyEntriesWithDesignsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(AerialSurveyEntryWithDesignToJSON)),
        'meta': PaginationMetaToJSON(value.meta),
        'message': value.message,
    };
}

