/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Request for polling Microsoft access token.
 * @export
 * @interface MicrosoftPollTokenRequest
 */
export interface MicrosoftPollTokenRequest {
    /**
     * 
     * @type {string}
     * @memberof MicrosoftPollTokenRequest
     */
    state: string;
}

/**
 * Check if a given object implements the MicrosoftPollTokenRequest interface.
 */
export function instanceOfMicrosoftPollTokenRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "state" in value;

    return isInstance;
}

export function MicrosoftPollTokenRequestFromJSON(json: any): MicrosoftPollTokenRequest {
    return MicrosoftPollTokenRequestFromJSONTyped(json, false);
}

export function MicrosoftPollTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MicrosoftPollTokenRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'state': json['state'],
    };
}

export function MicrosoftPollTokenRequestToJSON(value?: MicrosoftPollTokenRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'state': value.state,
    };
}

