/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AerialSurveyFileProject } from './AerialSurveyFileProject';
import {
    AerialSurveyFileProjectFromJSON,
    AerialSurveyFileProjectFromJSONTyped,
    AerialSurveyFileProjectToJSON,
} from './AerialSurveyFileProject';
import type { OutputFileContext } from './OutputFileContext';
import {
    OutputFileContextFromJSON,
    OutputFileContextFromJSONTyped,
    OutputFileContextToJSON,
} from './OutputFileContext';

/**
 * Model output file resource object
 * @export
 * @interface OutputFile
 */
export interface OutputFile {
    /**
     * 
     * @type {number}
     * @memberof OutputFile
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof OutputFile
     */
    projectId: number | null;
    /**
     * 
     * @type {number}
     * @memberof OutputFile
     */
    contextId: number | null;
    /**
     * 
     * @type {string}
     * @memberof OutputFile
     */
    contextType: string | null;
    /**
     * 
     * @type {string}
     * @memberof OutputFile
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof OutputFile
     */
    path: string;
    /**
     * 
     * @type {string}
     * @memberof OutputFile
     */
    disk: string;
    /**
     * 
     * @type {object}
     * @memberof OutputFile
     */
    metadata?: object | null;
    /**
     * Temporary url for accessing the file (expires in 1 hour)
     * @type {string}
     * @memberof OutputFile
     */
    url?: string;
    /**
     * 
     * @type {Date}
     * @memberof OutputFile
     */
    createdAt: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof OutputFile
     */
    updatedAt: Date | null;
    /**
     * 
     * @type {AerialSurveyFileProject}
     * @memberof OutputFile
     */
    project?: AerialSurveyFileProject | null;
    /**
     * 
     * @type {OutputFileContext}
     * @memberof OutputFile
     */
    context?: OutputFileContext | null;
}

/**
 * Check if a given object implements the OutputFile interface.
 */
export function instanceOfOutputFile(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "projectId" in value;
    isInstance = isInstance && "contextId" in value;
    isInstance = isInstance && "contextType" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "path" in value;
    isInstance = isInstance && "disk" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "updatedAt" in value;

    return isInstance;
}

export function OutputFileFromJSON(json: any): OutputFile {
    return OutputFileFromJSONTyped(json, false);
}

export function OutputFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): OutputFile {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'projectId': json['project_id'],
        'contextId': json['context_id'],
        'contextType': json['context_type'],
        'name': json['name'],
        'path': json['path'],
        'disk': json['disk'],
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'createdAt': (json['created_at'] === null ? null : new Date(json['created_at'])),
        'updatedAt': (json['updated_at'] === null ? null : new Date(json['updated_at'])),
        'project': !exists(json, 'project') ? undefined : AerialSurveyFileProjectFromJSON(json['project']),
        'context': !exists(json, 'context') ? undefined : OutputFileContextFromJSON(json['context']),
    };
}

export function OutputFileToJSON(value?: OutputFile | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'project_id': value.projectId,
        'context_id': value.contextId,
        'context_type': value.contextType,
        'name': value.name,
        'path': value.path,
        'disk': value.disk,
        'metadata': value.metadata,
        'url': value.url,
        'created_at': (value.createdAt === null ? null : value.createdAt.toISOString()),
        'updated_at': (value.updatedAt === null ? null : value.updatedAt.toISOString()),
        'project': AerialSurveyFileProjectToJSON(value.project),
        'context': OutputFileContextToJSON(value.context),
    };
}

