/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ColumnMapping } from './ColumnMapping';
import {
    ColumnMappingFromJSON,
    ColumnMappingFromJSONTyped,
    ColumnMappingToJSON,
} from './ColumnMapping';

/**
 * Show column mapping response object.
 * @export
 * @interface ShowColumnMappingResponse
 */
export interface ShowColumnMappingResponse {
    /**
     * 
     * @type {ColumnMapping}
     * @memberof ShowColumnMappingResponse
     */
    data: ColumnMapping;
    /**
     * 
     * @type {string}
     * @memberof ShowColumnMappingResponse
     */
    message: string;
}

/**
 * Check if a given object implements the ShowColumnMappingResponse interface.
 */
export function instanceOfShowColumnMappingResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function ShowColumnMappingResponseFromJSON(json: any): ShowColumnMappingResponse {
    return ShowColumnMappingResponseFromJSONTyped(json, false);
}

export function ShowColumnMappingResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShowColumnMappingResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ColumnMappingFromJSON(json['data']),
        'message': json['message'],
    };
}

export function ShowColumnMappingResponseToJSON(value?: ShowColumnMappingResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ColumnMappingToJSON(value.data),
        'message': value.message,
    };
}

