/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BetaVar } from './BetaVar';
import {
    BetaVarFromJSON,
    BetaVarFromJSONTyped,
    BetaVarToJSON,
} from './BetaVar';

/**
 * Show beta var response object.
 * @export
 * @interface ShowBetaVarResponse
 */
export interface ShowBetaVarResponse {
    /**
     * 
     * @type {BetaVar}
     * @memberof ShowBetaVarResponse
     */
    data: BetaVar;
    /**
     * 
     * @type {string}
     * @memberof ShowBetaVarResponse
     */
    message: string;
}

/**
 * Check if a given object implements the ShowBetaVarResponse interface.
 */
export function instanceOfShowBetaVarResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function ShowBetaVarResponseFromJSON(json: any): ShowBetaVarResponse {
    return ShowBetaVarResponseFromJSONTyped(json, false);
}

export function ShowBetaVarResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShowBetaVarResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': BetaVarFromJSON(json['data']),
        'message': json['message'],
    };
}

export function ShowBetaVarResponseToJSON(value?: ShowBetaVarResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': BetaVarToJSON(value.data),
        'message': value.message,
    };
}

