/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Region } from './Region';
import {
    RegionFromJSON,
    RegionFromJSONTyped,
    RegionToJSON,
} from './Region';

/**
 * Show region response object.
 * @export
 * @interface ShowRegionResponse
 */
export interface ShowRegionResponse {
    /**
     * 
     * @type {Region}
     * @memberof ShowRegionResponse
     */
    data: Region;
    /**
     * 
     * @type {string}
     * @memberof ShowRegionResponse
     */
    message: string;
}

/**
 * Check if a given object implements the ShowRegionResponse interface.
 */
export function instanceOfShowRegionResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function ShowRegionResponseFromJSON(json: any): ShowRegionResponse {
    return ShowRegionResponseFromJSONTyped(json, false);
}

export function ShowRegionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShowRegionResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': RegionFromJSON(json['data']),
        'message': json['message'],
    };
}

export function ShowRegionResponseToJSON(value?: ShowRegionResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': RegionToJSON(value.data),
        'message': value.message,
    };
}

