/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StoreMultipleCovarBetasResponseItem } from './StoreMultipleCovarBetasResponseItem';
import {
    StoreMultipleCovarBetasResponseItemFromJSON,
    StoreMultipleCovarBetasResponseItemFromJSONTyped,
    StoreMultipleCovarBetasResponseItemToJSON,
} from './StoreMultipleCovarBetasResponseItem';

/**
 * Store multiple covar betas response object.
 * @export
 * @interface StoreMultipleCovarBetasResponse
 */
export interface StoreMultipleCovarBetasResponse {
    /**
     * 
     * @type {Array<StoreMultipleCovarBetasResponseItem>}
     * @memberof StoreMultipleCovarBetasResponse
     */
    data: Array<StoreMultipleCovarBetasResponseItem>;
    /**
     * 
     * @type {string}
     * @memberof StoreMultipleCovarBetasResponse
     */
    message: string;
}

/**
 * Check if a given object implements the StoreMultipleCovarBetasResponse interface.
 */
export function instanceOfStoreMultipleCovarBetasResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function StoreMultipleCovarBetasResponseFromJSON(json: any): StoreMultipleCovarBetasResponse {
    return StoreMultipleCovarBetasResponseFromJSONTyped(json, false);
}

export function StoreMultipleCovarBetasResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreMultipleCovarBetasResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(StoreMultipleCovarBetasResponseItemFromJSON)),
        'message': json['message'],
    };
}

export function StoreMultipleCovarBetasResponseToJSON(value?: StoreMultipleCovarBetasResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(StoreMultipleCovarBetasResponseItemToJSON)),
        'message': value.message,
    };
}

