/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StoreMultipleColumnMappingsResponseItem } from './StoreMultipleColumnMappingsResponseItem';
import {
    StoreMultipleColumnMappingsResponseItemFromJSON,
    StoreMultipleColumnMappingsResponseItemFromJSONTyped,
    StoreMultipleColumnMappingsResponseItemToJSON,
} from './StoreMultipleColumnMappingsResponseItem';

/**
 * Store multiple column mappings response object.
 * @export
 * @interface StoreMultipleColumnMappingsResponse
 */
export interface StoreMultipleColumnMappingsResponse {
    /**
     * 
     * @type {Array<StoreMultipleColumnMappingsResponseItem>}
     * @memberof StoreMultipleColumnMappingsResponse
     */
    data: Array<StoreMultipleColumnMappingsResponseItem>;
    /**
     * 
     * @type {string}
     * @memberof StoreMultipleColumnMappingsResponse
     */
    message: string;
}

/**
 * Check if a given object implements the StoreMultipleColumnMappingsResponse interface.
 */
export function instanceOfStoreMultipleColumnMappingsResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function StoreMultipleColumnMappingsResponseFromJSON(json: any): StoreMultipleColumnMappingsResponse {
    return StoreMultipleColumnMappingsResponseFromJSONTyped(json, false);
}

export function StoreMultipleColumnMappingsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreMultipleColumnMappingsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(StoreMultipleColumnMappingsResponseItemFromJSON)),
        'message': json['message'],
    };
}

export function StoreMultipleColumnMappingsResponseToJSON(value?: StoreMultipleColumnMappingsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(StoreMultipleColumnMappingsResponseItemToJSON)),
        'message': value.message,
    };
}

