/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    AsyncMultipleKeyResponse,
    instanceOfAsyncMultipleKeyResponse,
    AsyncMultipleKeyResponseFromJSON,
    AsyncMultipleKeyResponseFromJSONTyped,
    AsyncMultipleKeyResponseToJSON,
} from './AsyncMultipleKeyResponse';
import {
    StoreMultiplePriorEntriesResponse,
    instanceOfStoreMultiplePriorEntriesResponse,
    StoreMultiplePriorEntriesResponseFromJSON,
    StoreMultiplePriorEntriesResponseFromJSONTyped,
    StoreMultiplePriorEntriesResponseToJSON,
} from './StoreMultiplePriorEntriesResponse';

/**
 * @type StoreMultiplePriorEntries200Response
 * 
 * @export
 */
export type StoreMultiplePriorEntries200Response = AsyncMultipleKeyResponse | StoreMultiplePriorEntriesResponse;

export function StoreMultiplePriorEntries200ResponseFromJSON(json: any): StoreMultiplePriorEntries200Response {
    return StoreMultiplePriorEntries200ResponseFromJSONTyped(json, false);
}

export function StoreMultiplePriorEntries200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreMultiplePriorEntries200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...AsyncMultipleKeyResponseFromJSONTyped(json, true), ...StoreMultiplePriorEntriesResponseFromJSONTyped(json, true) };
}

export function StoreMultiplePriorEntries200ResponseToJSON(value?: StoreMultiplePriorEntries200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfAsyncMultipleKeyResponse(value)) {
        return AsyncMultipleKeyResponseToJSON(value as AsyncMultipleKeyResponse);
    }
    if (instanceOfStoreMultiplePriorEntriesResponse(value)) {
        return StoreMultiplePriorEntriesResponseToJSON(value as StoreMultiplePriorEntriesResponse);
    }

    return {};
}

