/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    AsyncMultipleKeyResponse,
    instanceOfAsyncMultipleKeyResponse,
    AsyncMultipleKeyResponseFromJSON,
    AsyncMultipleKeyResponseFromJSONTyped,
    AsyncMultipleKeyResponseToJSON,
} from './AsyncMultipleKeyResponse';
import {
    StoreMultipleAircraftResponse,
    instanceOfStoreMultipleAircraftResponse,
    StoreMultipleAircraftResponseFromJSON,
    StoreMultipleAircraftResponseFromJSONTyped,
    StoreMultipleAircraftResponseToJSON,
} from './StoreMultipleAircraftResponse';

/**
 * @type StoreMultipleAircraft200Response
 * 
 * @export
 */
export type StoreMultipleAircraft200Response = AsyncMultipleKeyResponse | StoreMultipleAircraftResponse;

export function StoreMultipleAircraft200ResponseFromJSON(json: any): StoreMultipleAircraft200Response {
    return StoreMultipleAircraft200ResponseFromJSONTyped(json, false);
}

export function StoreMultipleAircraft200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreMultipleAircraft200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...AsyncMultipleKeyResponseFromJSONTyped(json, true), ...StoreMultipleAircraftResponseFromJSONTyped(json, true) };
}

export function StoreMultipleAircraft200ResponseToJSON(value?: StoreMultipleAircraft200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfAsyncMultipleKeyResponse(value)) {
        return AsyncMultipleKeyResponseToJSON(value as AsyncMultipleKeyResponse);
    }
    if (instanceOfStoreMultipleAircraftResponse(value)) {
        return StoreMultipleAircraftResponseToJSON(value as StoreMultipleAircraftResponse);
    }

    return {};
}

