/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StoreMultipleUsersResponseItem } from './StoreMultipleUsersResponseItem';
import {
    StoreMultipleUsersResponseItemFromJSON,
    StoreMultipleUsersResponseItemFromJSONTyped,
    StoreMultipleUsersResponseItemToJSON,
} from './StoreMultipleUsersResponseItem';

/**
 * Store multiple users response object.
 * @export
 * @interface StoreMultipleUsersResponse
 */
export interface StoreMultipleUsersResponse {
    /**
     * 
     * @type {Array<StoreMultipleUsersResponseItem>}
     * @memberof StoreMultipleUsersResponse
     */
    data: Array<StoreMultipleUsersResponseItem>;
    /**
     * 
     * @type {string}
     * @memberof StoreMultipleUsersResponse
     */
    message: string;
}

/**
 * Check if a given object implements the StoreMultipleUsersResponse interface.
 */
export function instanceOfStoreMultipleUsersResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function StoreMultipleUsersResponseFromJSON(json: any): StoreMultipleUsersResponse {
    return StoreMultipleUsersResponseFromJSONTyped(json, false);
}

export function StoreMultipleUsersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreMultipleUsersResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(StoreMultipleUsersResponseItemFromJSON)),
        'message': json['message'],
    };
}

export function StoreMultipleUsersResponseToJSON(value?: StoreMultipleUsersResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(StoreMultipleUsersResponseItemToJSON)),
        'message': value.message,
    };
}

