/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    StoreSurveyTypeRequest,
    instanceOfStoreSurveyTypeRequest,
    StoreSurveyTypeRequestFromJSON,
    StoreSurveyTypeRequestFromJSONTyped,
    StoreSurveyTypeRequestToJSON,
} from './StoreSurveyTypeRequest';
import {
    SurveyTypeForCountApi,
    instanceOfSurveyTypeForCountApi,
    SurveyTypeForCountApiFromJSON,
    SurveyTypeForCountApiFromJSONTyped,
    SurveyTypeForCountApiToJSON,
} from './SurveyTypeForCountApi';

/**
 * @type StoreMultipleSurveyTypesResponseItemData
 * 
 * @export
 */
export type StoreMultipleSurveyTypesResponseItemData = StoreSurveyTypeRequest | SurveyTypeForCountApi;

export function StoreMultipleSurveyTypesResponseItemDataFromJSON(json: any): StoreMultipleSurveyTypesResponseItemData {
    return StoreMultipleSurveyTypesResponseItemDataFromJSONTyped(json, false);
}

export function StoreMultipleSurveyTypesResponseItemDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreMultipleSurveyTypesResponseItemData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...StoreSurveyTypeRequestFromJSONTyped(json, true), ...SurveyTypeForCountApiFromJSONTyped(json, true) };
}

export function StoreMultipleSurveyTypesResponseItemDataToJSON(value?: StoreMultipleSurveyTypesResponseItemData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfStoreSurveyTypeRequest(value)) {
        return StoreSurveyTypeRequestToJSON(value as StoreSurveyTypeRequest);
    }
    if (instanceOfSurveyTypeForCountApi(value)) {
        return SurveyTypeForCountApiToJSON(value as SurveyTypeForCountApi);
    }

    return {};
}

