/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StoreUserRequest } from './StoreUserRequest';
import {
    StoreUserRequestFromJSON,
    StoreUserRequestFromJSONTyped,
    StoreUserRequestToJSON,
} from './StoreUserRequest';

/**
 * Store multiple users request object.
 * @export
 * @interface StoreMultipleUsersRequest
 */
export interface StoreMultipleUsersRequest {
    /**
     * 
     * @type {Array<StoreUserRequest>}
     * @memberof StoreMultipleUsersRequest
     */
    data: Array<StoreUserRequest>;
}

/**
 * Check if a given object implements the StoreMultipleUsersRequest interface.
 */
export function instanceOfStoreMultipleUsersRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function StoreMultipleUsersRequestFromJSON(json: any): StoreMultipleUsersRequest {
    return StoreMultipleUsersRequestFromJSONTyped(json, false);
}

export function StoreMultipleUsersRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreMultipleUsersRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(StoreUserRequestFromJSON)),
    };
}

export function StoreMultipleUsersRequestToJSON(value?: StoreMultipleUsersRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(StoreUserRequestToJSON)),
    };
}

