/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StoreCovarCategoryRequest } from './StoreCovarCategoryRequest';
import {
    StoreCovarCategoryRequestFromJSON,
    StoreCovarCategoryRequestFromJSONTyped,
    StoreCovarCategoryRequestToJSON,
} from './StoreCovarCategoryRequest';

/**
 * Store multiple covars categories request object.
 * @export
 * @interface StoreMultipleCovarCategoriesRequest
 */
export interface StoreMultipleCovarCategoriesRequest {
    /**
     * 
     * @type {Array<StoreCovarCategoryRequest>}
     * @memberof StoreMultipleCovarCategoriesRequest
     */
    data: Array<StoreCovarCategoryRequest>;
}

/**
 * Check if a given object implements the StoreMultipleCovarCategoriesRequest interface.
 */
export function instanceOfStoreMultipleCovarCategoriesRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function StoreMultipleCovarCategoriesRequestFromJSON(json: any): StoreMultipleCovarCategoriesRequest {
    return StoreMultipleCovarCategoriesRequestFromJSONTyped(json, false);
}

export function StoreMultipleCovarCategoriesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreMultipleCovarCategoriesRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(StoreCovarCategoryRequestFromJSON)),
    };
}

export function StoreMultipleCovarCategoriesRequestToJSON(value?: StoreMultipleCovarCategoriesRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(StoreCovarCategoryRequestToJSON)),
    };
}

