/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StoreMultipleSurveyTypesResponseItemData } from './StoreMultipleSurveyTypesResponseItemData';
import {
    StoreMultipleSurveyTypesResponseItemDataFromJSON,
    StoreMultipleSurveyTypesResponseItemDataFromJSONTyped,
    StoreMultipleSurveyTypesResponseItemDataToJSON,
} from './StoreMultipleSurveyTypesResponseItemData';

/**
 * Store multiple species response item object.
 * @export
 * @interface StoreMultipleSurveyTypesResponseItem
 */
export interface StoreMultipleSurveyTypesResponseItem {
    /**
     * 
     * @type {StoreMultipleSurveyTypesResponseItemData}
     * @memberof StoreMultipleSurveyTypesResponseItem
     */
    data: StoreMultipleSurveyTypesResponseItemData;
    /**
     * 
     * @type {boolean}
     * @memberof StoreMultipleSurveyTypesResponseItem
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof StoreMultipleSurveyTypesResponseItem
     */
    message: string;
    /**
     * 
     * @type {object}
     * @memberof StoreMultipleSurveyTypesResponseItem
     */
    errors?: object;
}

/**
 * Check if a given object implements the StoreMultipleSurveyTypesResponseItem interface.
 */
export function instanceOfStoreMultipleSurveyTypesResponseItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "success" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function StoreMultipleSurveyTypesResponseItemFromJSON(json: any): StoreMultipleSurveyTypesResponseItem {
    return StoreMultipleSurveyTypesResponseItemFromJSONTyped(json, false);
}

export function StoreMultipleSurveyTypesResponseItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreMultipleSurveyTypesResponseItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': StoreMultipleSurveyTypesResponseItemDataFromJSON(json['data']),
        'success': json['success'],
        'message': json['message'],
        'errors': !exists(json, 'errors') ? undefined : json['errors'],
    };
}

export function StoreMultipleSurveyTypesResponseItemToJSON(value?: StoreMultipleSurveyTypesResponseItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': StoreMultipleSurveyTypesResponseItemDataToJSON(value.data),
        'success': value.success,
        'message': value.message,
        'errors': value.errors,
    };
}

