/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StoreStratumRequest } from './StoreStratumRequest';
import {
    StoreStratumRequestFromJSON,
    StoreStratumRequestFromJSONTyped,
    StoreStratumRequestToJSON,
} from './StoreStratumRequest';

/**
 * Store multiple strata request object.
 * @export
 * @interface StoreMultipleStrataRequest
 */
export interface StoreMultipleStrataRequest {
    /**
     * 
     * @type {Array<StoreStratumRequest>}
     * @memberof StoreMultipleStrataRequest
     */
    data: Array<StoreStratumRequest>;
}

/**
 * Check if a given object implements the StoreMultipleStrataRequest interface.
 */
export function instanceOfStoreMultipleStrataRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function StoreMultipleStrataRequestFromJSON(json: any): StoreMultipleStrataRequest {
    return StoreMultipleStrataRequestFromJSONTyped(json, false);
}

export function StoreMultipleStrataRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreMultipleStrataRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(StoreStratumRequestFromJSON)),
    };
}

export function StoreMultipleStrataRequestToJSON(value?: StoreMultipleStrataRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(StoreStratumRequestToJSON)),
    };
}

