/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Request for creating a beta var record.
 *            `beta_id1` and `beta_id2` combination must be unique.
 * @export
 * @interface StoreBetaVarRequest
 */
export interface StoreBetaVarRequest {
    /**
     * 
     * @type {number}
     * @memberof StoreBetaVarRequest
     */
    betaId1: number;
    /**
     * 
     * @type {number}
     * @memberof StoreBetaVarRequest
     */
    betaId2: number;
    /**
     * 
     * @type {number}
     * @memberof StoreBetaVarRequest
     */
    vcov: number;
}

/**
 * Check if a given object implements the StoreBetaVarRequest interface.
 */
export function instanceOfStoreBetaVarRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "betaId1" in value;
    isInstance = isInstance && "betaId2" in value;
    isInstance = isInstance && "vcov" in value;

    return isInstance;
}

export function StoreBetaVarRequestFromJSON(json: any): StoreBetaVarRequest {
    return StoreBetaVarRequestFromJSONTyped(json, false);
}

export function StoreBetaVarRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreBetaVarRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'betaId1': json['beta_id1'],
        'betaId2': json['beta_id2'],
        'vcov': json['vcov'],
    };
}

export function StoreBetaVarRequestToJSON(value?: StoreBetaVarRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'beta_id1': value.betaId1,
        'beta_id2': value.betaId2,
        'vcov': value.vcov,
    };
}

