/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Project } from './Project';
import {
    ProjectFromJSON,
    ProjectFromJSONTyped,
    ProjectToJSON,
} from './Project';

/**
 * Store project response object.
 * @export
 * @interface StoreProjectResponse
 */
export interface StoreProjectResponse {
    /**
     * 
     * @type {Project}
     * @memberof StoreProjectResponse
     */
    data: Project;
    /**
     * 
     * @type {string}
     * @memberof StoreProjectResponse
     */
    message: string;
}

/**
 * Check if a given object implements the StoreProjectResponse interface.
 */
export function instanceOfStoreProjectResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function StoreProjectResponseFromJSON(json: any): StoreProjectResponse {
    return StoreProjectResponseFromJSONTyped(json, false);
}

export function StoreProjectResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreProjectResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ProjectFromJSON(json['data']),
        'message': json['message'],
    };
}

export function StoreProjectResponseToJSON(value?: StoreProjectResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ProjectToJSON(value.data),
        'message': value.message,
    };
}

