/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StoreMultipleColumnMappingsResponseItemData } from './StoreMultipleColumnMappingsResponseItemData';
import {
    StoreMultipleColumnMappingsResponseItemDataFromJSON,
    StoreMultipleColumnMappingsResponseItemDataFromJSONTyped,
    StoreMultipleColumnMappingsResponseItemDataToJSON,
} from './StoreMultipleColumnMappingsResponseItemData';

/**
 * Store multiple column mappings response item object.
 * @export
 * @interface StoreMultipleColumnMappingsResponseItem
 */
export interface StoreMultipleColumnMappingsResponseItem {
    /**
     * 
     * @type {StoreMultipleColumnMappingsResponseItemData}
     * @memberof StoreMultipleColumnMappingsResponseItem
     */
    data: StoreMultipleColumnMappingsResponseItemData;
    /**
     * 
     * @type {boolean}
     * @memberof StoreMultipleColumnMappingsResponseItem
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof StoreMultipleColumnMappingsResponseItem
     */
    message: string;
    /**
     * 
     * @type {object}
     * @memberof StoreMultipleColumnMappingsResponseItem
     */
    errors?: object;
}

/**
 * Check if a given object implements the StoreMultipleColumnMappingsResponseItem interface.
 */
export function instanceOfStoreMultipleColumnMappingsResponseItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "success" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function StoreMultipleColumnMappingsResponseItemFromJSON(json: any): StoreMultipleColumnMappingsResponseItem {
    return StoreMultipleColumnMappingsResponseItemFromJSONTyped(json, false);
}

export function StoreMultipleColumnMappingsResponseItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreMultipleColumnMappingsResponseItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': StoreMultipleColumnMappingsResponseItemDataFromJSON(json['data']),
        'success': json['success'],
        'message': json['message'],
        'errors': !exists(json, 'errors') ? undefined : json['errors'],
    };
}

export function StoreMultipleColumnMappingsResponseItemToJSON(value?: StoreMultipleColumnMappingsResponseItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': StoreMultipleColumnMappingsResponseItemDataToJSON(value.data),
        'success': value.success,
        'message': value.message,
        'errors': value.errors,
    };
}

