/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StoreMultipleAnalysisUnitVersionsResponseItemData } from './StoreMultipleAnalysisUnitVersionsResponseItemData';
import {
    StoreMultipleAnalysisUnitVersionsResponseItemDataFromJSON,
    StoreMultipleAnalysisUnitVersionsResponseItemDataFromJSONTyped,
    StoreMultipleAnalysisUnitVersionsResponseItemDataToJSON,
} from './StoreMultipleAnalysisUnitVersionsResponseItemData';

/**
 * Store multiple analysis unit versions response item object.
 * @export
 * @interface StoreMultipleAnalysisUnitVersionsResponseItem
 */
export interface StoreMultipleAnalysisUnitVersionsResponseItem {
    /**
     * 
     * @type {StoreMultipleAnalysisUnitVersionsResponseItemData}
     * @memberof StoreMultipleAnalysisUnitVersionsResponseItem
     */
    data: StoreMultipleAnalysisUnitVersionsResponseItemData;
    /**
     * 
     * @type {boolean}
     * @memberof StoreMultipleAnalysisUnitVersionsResponseItem
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof StoreMultipleAnalysisUnitVersionsResponseItem
     */
    message: string;
    /**
     * 
     * @type {object}
     * @memberof StoreMultipleAnalysisUnitVersionsResponseItem
     */
    errors?: object;
}

/**
 * Check if a given object implements the StoreMultipleAnalysisUnitVersionsResponseItem interface.
 */
export function instanceOfStoreMultipleAnalysisUnitVersionsResponseItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "success" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function StoreMultipleAnalysisUnitVersionsResponseItemFromJSON(json: any): StoreMultipleAnalysisUnitVersionsResponseItem {
    return StoreMultipleAnalysisUnitVersionsResponseItemFromJSONTyped(json, false);
}

export function StoreMultipleAnalysisUnitVersionsResponseItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreMultipleAnalysisUnitVersionsResponseItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': StoreMultipleAnalysisUnitVersionsResponseItemDataFromJSON(json['data']),
        'success': json['success'],
        'message': json['message'],
        'errors': !exists(json, 'errors') ? undefined : json['errors'],
    };
}

export function StoreMultipleAnalysisUnitVersionsResponseItemToJSON(value?: StoreMultipleAnalysisUnitVersionsResponseItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': StoreMultipleAnalysisUnitVersionsResponseItemDataToJSON(value.data),
        'success': value.success,
        'message': value.message,
        'errors': value.errors,
    };
}

