/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    ProjectAgeClass,
    instanceOfProjectAgeClass,
    ProjectAgeClassFromJSON,
    ProjectAgeClassFromJSONTyped,
    ProjectAgeClassToJSON,
} from './ProjectAgeClass';
import {
    StoreProjectAgeClassRequest,
    instanceOfStoreProjectAgeClassRequest,
    StoreProjectAgeClassRequestFromJSON,
    StoreProjectAgeClassRequestFromJSONTyped,
    StoreProjectAgeClassRequestToJSON,
} from './StoreProjectAgeClassRequest';

/**
 * @type StoreMultipleProjectAgeClassesResponseItemData
 * 
 * @export
 */
export type StoreMultipleProjectAgeClassesResponseItemData = ProjectAgeClass | StoreProjectAgeClassRequest;

export function StoreMultipleProjectAgeClassesResponseItemDataFromJSON(json: any): StoreMultipleProjectAgeClassesResponseItemData {
    return StoreMultipleProjectAgeClassesResponseItemDataFromJSONTyped(json, false);
}

export function StoreMultipleProjectAgeClassesResponseItemDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreMultipleProjectAgeClassesResponseItemData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...ProjectAgeClassFromJSONTyped(json, true), ...StoreProjectAgeClassRequestFromJSONTyped(json, true) };
}

export function StoreMultipleProjectAgeClassesResponseItemDataToJSON(value?: StoreMultipleProjectAgeClassesResponseItemData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfProjectAgeClass(value)) {
        return ProjectAgeClassToJSON(value as ProjectAgeClass);
    }
    if (instanceOfStoreProjectAgeClassRequest(value)) {
        return StoreProjectAgeClassRequestToJSON(value as StoreProjectAgeClassRequest);
    }

    return {};
}

