/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    CovarCategory,
    instanceOfCovarCategory,
    CovarCategoryFromJSON,
    CovarCategoryFromJSONTyped,
    CovarCategoryToJSON,
} from './CovarCategory';
import {
    StoreCovarCategoryRequest,
    instanceOfStoreCovarCategoryRequest,
    StoreCovarCategoryRequestFromJSON,
    StoreCovarCategoryRequestFromJSONTyped,
    StoreCovarCategoryRequestToJSON,
} from './StoreCovarCategoryRequest';

/**
 * @type StoreMultipleCovarCategoriesResponseItemData
 * 
 * @export
 */
export type StoreMultipleCovarCategoriesResponseItemData = CovarCategory | StoreCovarCategoryRequest;

export function StoreMultipleCovarCategoriesResponseItemDataFromJSON(json: any): StoreMultipleCovarCategoriesResponseItemData {
    return StoreMultipleCovarCategoriesResponseItemDataFromJSONTyped(json, false);
}

export function StoreMultipleCovarCategoriesResponseItemDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreMultipleCovarCategoriesResponseItemData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...CovarCategoryFromJSONTyped(json, true), ...StoreCovarCategoryRequestFromJSONTyped(json, true) };
}

export function StoreMultipleCovarCategoriesResponseItemDataToJSON(value?: StoreMultipleCovarCategoriesResponseItemData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfCovarCategory(value)) {
        return CovarCategoryToJSON(value as CovarCategory);
    }
    if (instanceOfStoreCovarCategoryRequest(value)) {
        return StoreCovarCategoryRequestToJSON(value as StoreCovarCategoryRequest);
    }

    return {};
}

