/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StoreOutputStepRequest } from './StoreOutputStepRequest';
import {
    StoreOutputStepRequestFromJSON,
    StoreOutputStepRequestFromJSONTyped,
    StoreOutputStepRequestToJSON,
} from './StoreOutputStepRequest';

/**
 * Store multiple output steps request object.
 * @export
 * @interface StoreMultipleOutputStepsRequest
 */
export interface StoreMultipleOutputStepsRequest {
    /**
     * 
     * @type {Array<StoreOutputStepRequest>}
     * @memberof StoreMultipleOutputStepsRequest
     */
    data: Array<StoreOutputStepRequest>;
}

/**
 * Check if a given object implements the StoreMultipleOutputStepsRequest interface.
 */
export function instanceOfStoreMultipleOutputStepsRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function StoreMultipleOutputStepsRequestFromJSON(json: any): StoreMultipleOutputStepsRequest {
    return StoreMultipleOutputStepsRequestFromJSONTyped(json, false);
}

export function StoreMultipleOutputStepsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreMultipleOutputStepsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(StoreOutputStepRequestFromJSON)),
    };
}

export function StoreMultipleOutputStepsRequestToJSON(value?: StoreMultipleOutputStepsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(StoreOutputStepRequestToJSON)),
    };
}

