/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    AsyncMultipleKeyResponse,
    instanceOfAsyncMultipleKeyResponse,
    AsyncMultipleKeyResponseFromJSON,
    AsyncMultipleKeyResponseFromJSONTyped,
    AsyncMultipleKeyResponseToJSON,
} from './AsyncMultipleKeyResponse';
import {
    StoreMultipleEntryColumnMappingVersionsResponse,
    instanceOfStoreMultipleEntryColumnMappingVersionsResponse,
    StoreMultipleEntryColumnMappingVersionsResponseFromJSON,
    StoreMultipleEntryColumnMappingVersionsResponseFromJSONTyped,
    StoreMultipleEntryColumnMappingVersionsResponseToJSON,
} from './StoreMultipleEntryColumnMappingVersionsResponse';

/**
 * @type StoreMultipleEntryColumnMappingVersions200Response
 * 
 * @export
 */
export type StoreMultipleEntryColumnMappingVersions200Response = AsyncMultipleKeyResponse | StoreMultipleEntryColumnMappingVersionsResponse;

export function StoreMultipleEntryColumnMappingVersions200ResponseFromJSON(json: any): StoreMultipleEntryColumnMappingVersions200Response {
    return StoreMultipleEntryColumnMappingVersions200ResponseFromJSONTyped(json, false);
}

export function StoreMultipleEntryColumnMappingVersions200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreMultipleEntryColumnMappingVersions200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...AsyncMultipleKeyResponseFromJSONTyped(json, true), ...StoreMultipleEntryColumnMappingVersionsResponseFromJSONTyped(json, true) };
}

export function StoreMultipleEntryColumnMappingVersions200ResponseToJSON(value?: StoreMultipleEntryColumnMappingVersions200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfAsyncMultipleKeyResponse(value)) {
        return AsyncMultipleKeyResponseToJSON(value as AsyncMultipleKeyResponse);
    }
    if (instanceOfStoreMultipleEntryColumnMappingVersionsResponse(value)) {
        return StoreMultipleEntryColumnMappingVersionsResponseToJSON(value as StoreMultipleEntryColumnMappingVersionsResponse);
    }

    return {};
}

