/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EntryColumnMappingVersion } from './EntryColumnMappingVersion';
import {
    EntryColumnMappingVersionFromJSON,
    EntryColumnMappingVersionFromJSONTyped,
    EntryColumnMappingVersionToJSON,
} from './EntryColumnMappingVersion';

/**
 * Store entry column mapping response object.
 * @export
 * @interface StoreEntryColumnMappingVersionResponse
 */
export interface StoreEntryColumnMappingVersionResponse {
    /**
     * 
     * @type {EntryColumnMappingVersion}
     * @memberof StoreEntryColumnMappingVersionResponse
     */
    data: EntryColumnMappingVersion;
    /**
     * 
     * @type {string}
     * @memberof StoreEntryColumnMappingVersionResponse
     */
    message: string;
}

/**
 * Check if a given object implements the StoreEntryColumnMappingVersionResponse interface.
 */
export function instanceOfStoreEntryColumnMappingVersionResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function StoreEntryColumnMappingVersionResponseFromJSON(json: any): StoreEntryColumnMappingVersionResponse {
    return StoreEntryColumnMappingVersionResponseFromJSONTyped(json, false);
}

export function StoreEntryColumnMappingVersionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreEntryColumnMappingVersionResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': EntryColumnMappingVersionFromJSON(json['data']),
        'message': json['message'],
    };
}

export function StoreEntryColumnMappingVersionResponseToJSON(value?: StoreEntryColumnMappingVersionResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': EntryColumnMappingVersionToJSON(value.data),
        'message': value.message,
    };
}

