/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StoreMultipleCovarBinsResponseItemData } from './StoreMultipleCovarBinsResponseItemData';
import {
    StoreMultipleCovarBinsResponseItemDataFromJSON,
    StoreMultipleCovarBinsResponseItemDataFromJSONTyped,
    StoreMultipleCovarBinsResponseItemDataToJSON,
} from './StoreMultipleCovarBinsResponseItemData';

/**
 * Store multiple covar bins response item object.
 * @export
 * @interface StoreMultipleCovarBinsResponseItem
 */
export interface StoreMultipleCovarBinsResponseItem {
    /**
     * 
     * @type {StoreMultipleCovarBinsResponseItemData}
     * @memberof StoreMultipleCovarBinsResponseItem
     */
    data: StoreMultipleCovarBinsResponseItemData;
    /**
     * 
     * @type {boolean}
     * @memberof StoreMultipleCovarBinsResponseItem
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof StoreMultipleCovarBinsResponseItem
     */
    message: string;
    /**
     * 
     * @type {object}
     * @memberof StoreMultipleCovarBinsResponseItem
     */
    errors?: object;
}

/**
 * Check if a given object implements the StoreMultipleCovarBinsResponseItem interface.
 */
export function instanceOfStoreMultipleCovarBinsResponseItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "success" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function StoreMultipleCovarBinsResponseItemFromJSON(json: any): StoreMultipleCovarBinsResponseItem {
    return StoreMultipleCovarBinsResponseItemFromJSONTyped(json, false);
}

export function StoreMultipleCovarBinsResponseItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreMultipleCovarBinsResponseItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': StoreMultipleCovarBinsResponseItemDataFromJSON(json['data']),
        'success': json['success'],
        'message': json['message'],
        'errors': !exists(json, 'errors') ? undefined : json['errors'],
    };
}

export function StoreMultipleCovarBinsResponseItemToJSON(value?: StoreMultipleCovarBinsResponseItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': StoreMultipleCovarBinsResponseItemDataToJSON(value.data),
        'success': value.success,
        'message': value.message,
        'errors': value.errors,
    };
}

