/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StoreMultipleOutputsResponseItem } from './StoreMultipleOutputsResponseItem';
import {
    StoreMultipleOutputsResponseItemFromJSON,
    StoreMultipleOutputsResponseItemFromJSONTyped,
    StoreMultipleOutputsResponseItemToJSON,
} from './StoreMultipleOutputsResponseItem';

/**
 * Store multiple outputs response object.
 * @export
 * @interface StoreMultipleOutputsResponse
 */
export interface StoreMultipleOutputsResponse {
    /**
     * 
     * @type {Array<StoreMultipleOutputsResponseItem>}
     * @memberof StoreMultipleOutputsResponse
     */
    data: Array<StoreMultipleOutputsResponseItem>;
    /**
     * 
     * @type {string}
     * @memberof StoreMultipleOutputsResponse
     */
    message: string;
}

/**
 * Check if a given object implements the StoreMultipleOutputsResponse interface.
 */
export function instanceOfStoreMultipleOutputsResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function StoreMultipleOutputsResponseFromJSON(json: any): StoreMultipleOutputsResponse {
    return StoreMultipleOutputsResponseFromJSONTyped(json, false);
}

export function StoreMultipleOutputsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreMultipleOutputsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(StoreMultipleOutputsResponseItemFromJSON)),
        'message': json['message'],
    };
}

export function StoreMultipleOutputsResponseToJSON(value?: StoreMultipleOutputsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(StoreMultipleOutputsResponseItemToJSON)),
        'message': value.message,
    };
}

