/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StoreMultipleAerialSurveyEntriesResponseItemData } from './StoreMultipleAerialSurveyEntriesResponseItemData';
import {
    StoreMultipleAerialSurveyEntriesResponseItemDataFromJSON,
    StoreMultipleAerialSurveyEntriesResponseItemDataFromJSONTyped,
    StoreMultipleAerialSurveyEntriesResponseItemDataToJSON,
} from './StoreMultipleAerialSurveyEntriesResponseItemData';

/**
 * Store multiple aerial survey entries response item object.
 * @export
 * @interface StoreMultipleAerialSurveyEntriesResponseItem
 */
export interface StoreMultipleAerialSurveyEntriesResponseItem {
    /**
     * 
     * @type {StoreMultipleAerialSurveyEntriesResponseItemData}
     * @memberof StoreMultipleAerialSurveyEntriesResponseItem
     */
    data: StoreMultipleAerialSurveyEntriesResponseItemData;
    /**
     * 
     * @type {boolean}
     * @memberof StoreMultipleAerialSurveyEntriesResponseItem
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof StoreMultipleAerialSurveyEntriesResponseItem
     */
    message: string;
    /**
     * 
     * @type {object}
     * @memberof StoreMultipleAerialSurveyEntriesResponseItem
     */
    errors?: object;
}

/**
 * Check if a given object implements the StoreMultipleAerialSurveyEntriesResponseItem interface.
 */
export function instanceOfStoreMultipleAerialSurveyEntriesResponseItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "success" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function StoreMultipleAerialSurveyEntriesResponseItemFromJSON(json: any): StoreMultipleAerialSurveyEntriesResponseItem {
    return StoreMultipleAerialSurveyEntriesResponseItemFromJSONTyped(json, false);
}

export function StoreMultipleAerialSurveyEntriesResponseItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreMultipleAerialSurveyEntriesResponseItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': StoreMultipleAerialSurveyEntriesResponseItemDataFromJSON(json['data']),
        'success': json['success'],
        'message': json['message'],
        'errors': !exists(json, 'errors') ? undefined : json['errors'],
    };
}

export function StoreMultipleAerialSurveyEntriesResponseItemToJSON(value?: StoreMultipleAerialSurveyEntriesResponseItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': StoreMultipleAerialSurveyEntriesResponseItemDataToJSON(value.data),
        'success': value.success,
        'message': value.message,
        'errors': value.errors,
    };
}

