/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StoreColumnMappingRequest } from './StoreColumnMappingRequest';
import {
    StoreColumnMappingRequestFromJSON,
    StoreColumnMappingRequestFromJSONTyped,
    StoreColumnMappingRequestToJSON,
} from './StoreColumnMappingRequest';

/**
 * Store multiple entry column mapping versions request object.
 * @export
 * @interface StoreMultipleEntryColumnMappingVersionsRequest
 */
export interface StoreMultipleEntryColumnMappingVersionsRequest {
    /**
     * 
     * @type {Array<StoreColumnMappingRequest>}
     * @memberof StoreMultipleEntryColumnMappingVersionsRequest
     */
    data: Array<StoreColumnMappingRequest>;
}

/**
 * Check if a given object implements the StoreMultipleEntryColumnMappingVersionsRequest interface.
 */
export function instanceOfStoreMultipleEntryColumnMappingVersionsRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function StoreMultipleEntryColumnMappingVersionsRequestFromJSON(json: any): StoreMultipleEntryColumnMappingVersionsRequest {
    return StoreMultipleEntryColumnMappingVersionsRequestFromJSONTyped(json, false);
}

export function StoreMultipleEntryColumnMappingVersionsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreMultipleEntryColumnMappingVersionsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(StoreColumnMappingRequestFromJSON)),
    };
}

export function StoreMultipleEntryColumnMappingVersionsRequestToJSON(value?: StoreMultipleEntryColumnMappingVersionsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(StoreColumnMappingRequestToJSON)),
    };
}

