/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Request for creating a count category record.
 * @export
 * @interface StoreCountCategoryRequest
 */
export interface StoreCountCategoryRequest {
    /**
     * 
     * @type {number}
     * @memberof StoreCountCategoryRequest
     */
    surveyTypeId: number;
    /**
     * 
     * @type {string}
     * @memberof StoreCountCategoryRequest
     */
    abbreviation: string;
    /**
     * 
     * @type {string}
     * @memberof StoreCountCategoryRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof StoreCountCategoryRequest
     */
    ageClass?: StoreCountCategoryRequestAgeClassEnum;
    /**
     * 
     * @type {string}
     * @memberof StoreCountCategoryRequest
     */
    sex?: StoreCountCategoryRequestSexEnum;
}


/**
 * @export
 */
export const StoreCountCategoryRequestAgeClassEnum = {
    Adult: 'Adult',
    YoungOfYear: 'Young of Year',
    Juvenile: 'Juvenile',
    Subadult: 'Subadult'
} as const;
export type StoreCountCategoryRequestAgeClassEnum = typeof StoreCountCategoryRequestAgeClassEnum[keyof typeof StoreCountCategoryRequestAgeClassEnum];

/**
 * @export
 */
export const StoreCountCategoryRequestSexEnum = {
    Male: 'Male',
    Female: 'Female'
} as const;
export type StoreCountCategoryRequestSexEnum = typeof StoreCountCategoryRequestSexEnum[keyof typeof StoreCountCategoryRequestSexEnum];


/**
 * Check if a given object implements the StoreCountCategoryRequest interface.
 */
export function instanceOfStoreCountCategoryRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "surveyTypeId" in value;
    isInstance = isInstance && "abbreviation" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function StoreCountCategoryRequestFromJSON(json: any): StoreCountCategoryRequest {
    return StoreCountCategoryRequestFromJSONTyped(json, false);
}

export function StoreCountCategoryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreCountCategoryRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'surveyTypeId': json['survey_type_id'],
        'abbreviation': json['abbreviation'],
        'name': json['name'],
        'ageClass': !exists(json, 'age_class') ? undefined : json['age_class'],
        'sex': !exists(json, 'sex') ? undefined : json['sex'],
    };
}

export function StoreCountCategoryRequestToJSON(value?: StoreCountCategoryRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'survey_type_id': value.surveyTypeId,
        'abbreviation': value.abbreviation,
        'name': value.name,
        'age_class': value.ageClass,
        'sex': value.sex,
    };
}

