/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StoreMultiplePriorEntriesResponseItemData } from './StoreMultiplePriorEntriesResponseItemData';
import {
    StoreMultiplePriorEntriesResponseItemDataFromJSON,
    StoreMultiplePriorEntriesResponseItemDataFromJSONTyped,
    StoreMultiplePriorEntriesResponseItemDataToJSON,
} from './StoreMultiplePriorEntriesResponseItemData';

/**
 * Store multiple prior entries response item object.
 * @export
 * @interface StoreMultiplePriorEntriesResponseItem
 */
export interface StoreMultiplePriorEntriesResponseItem {
    /**
     * 
     * @type {StoreMultiplePriorEntriesResponseItemData}
     * @memberof StoreMultiplePriorEntriesResponseItem
     */
    data: StoreMultiplePriorEntriesResponseItemData;
    /**
     * 
     * @type {boolean}
     * @memberof StoreMultiplePriorEntriesResponseItem
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof StoreMultiplePriorEntriesResponseItem
     */
    message: string;
    /**
     * 
     * @type {object}
     * @memberof StoreMultiplePriorEntriesResponseItem
     */
    errors?: object;
}

/**
 * Check if a given object implements the StoreMultiplePriorEntriesResponseItem interface.
 */
export function instanceOfStoreMultiplePriorEntriesResponseItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "success" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function StoreMultiplePriorEntriesResponseItemFromJSON(json: any): StoreMultiplePriorEntriesResponseItem {
    return StoreMultiplePriorEntriesResponseItemFromJSONTyped(json, false);
}

export function StoreMultiplePriorEntriesResponseItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreMultiplePriorEntriesResponseItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': StoreMultiplePriorEntriesResponseItemDataFromJSON(json['data']),
        'success': json['success'],
        'message': json['message'],
        'errors': !exists(json, 'errors') ? undefined : json['errors'],
    };
}

export function StoreMultiplePriorEntriesResponseItemToJSON(value?: StoreMultiplePriorEntriesResponseItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': StoreMultiplePriorEntriesResponseItemDataToJSON(value.data),
        'success': value.success,
        'message': value.message,
        'errors': value.errors,
    };
}

