/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Request for creating an analysis unit record.
 *             `version_id` and `number` combination must be unique.
 *              within the `location.analysis_units` table.
 * @export
 * @interface StoreAnalysisUnitRequest
 */
export interface StoreAnalysisUnitRequest {
    /**
     * 
     * @type {number}
     * @memberof StoreAnalysisUnitRequest
     */
    versionId: number;
    /**
     * 
     * @type {number}
     * @memberof StoreAnalysisUnitRequest
     */
    number: number;
    /**
     * 
     * @type {string}
     * @memberof StoreAnalysisUnitRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof StoreAnalysisUnitRequest
     */
    abbreviation: string;
    /**
     * 
     * @type {number}
     * @memberof StoreAnalysisUnitRequest
     */
    sortOrder: number;
}

/**
 * Check if a given object implements the StoreAnalysisUnitRequest interface.
 */
export function instanceOfStoreAnalysisUnitRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "versionId" in value;
    isInstance = isInstance && "number" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "abbreviation" in value;
    isInstance = isInstance && "sortOrder" in value;

    return isInstance;
}

export function StoreAnalysisUnitRequestFromJSON(json: any): StoreAnalysisUnitRequest {
    return StoreAnalysisUnitRequestFromJSONTyped(json, false);
}

export function StoreAnalysisUnitRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreAnalysisUnitRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'versionId': json['version_id'],
        'number': json['number'],
        'name': json['name'],
        'abbreviation': json['abbreviation'],
        'sortOrder': json['sort_order'],
    };
}

export function StoreAnalysisUnitRequestToJSON(value?: StoreAnalysisUnitRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'version_id': value.versionId,
        'number': value.number,
        'name': value.name,
        'abbreviation': value.abbreviation,
        'sort_order': value.sortOrder,
    };
}

