/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StoreMultipleBetaVarsResponseItem } from './StoreMultipleBetaVarsResponseItem';
import {
    StoreMultipleBetaVarsResponseItemFromJSON,
    StoreMultipleBetaVarsResponseItemFromJSONTyped,
    StoreMultipleBetaVarsResponseItemToJSON,
} from './StoreMultipleBetaVarsResponseItem';

/**
 * Store multiple beta vars response object.
 * @export
 * @interface StoreMultipleBetaVarsResponse
 */
export interface StoreMultipleBetaVarsResponse {
    /**
     * 
     * @type {Array<StoreMultipleBetaVarsResponseItem>}
     * @memberof StoreMultipleBetaVarsResponse
     */
    data: Array<StoreMultipleBetaVarsResponseItem>;
    /**
     * 
     * @type {string}
     * @memberof StoreMultipleBetaVarsResponse
     */
    message: string;
}

/**
 * Check if a given object implements the StoreMultipleBetaVarsResponse interface.
 */
export function instanceOfStoreMultipleBetaVarsResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function StoreMultipleBetaVarsResponseFromJSON(json: any): StoreMultipleBetaVarsResponse {
    return StoreMultipleBetaVarsResponseFromJSONTyped(json, false);
}

export function StoreMultipleBetaVarsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreMultipleBetaVarsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(StoreMultipleBetaVarsResponseItemFromJSON)),
        'message': json['message'],
    };
}

export function StoreMultipleBetaVarsResponseToJSON(value?: StoreMultipleBetaVarsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(StoreMultipleBetaVarsResponseItemToJSON)),
        'message': value.message,
    };
}

