/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StoreOutputRequest } from './StoreOutputRequest';
import {
    StoreOutputRequestFromJSON,
    StoreOutputRequestFromJSONTyped,
    StoreOutputRequestToJSON,
} from './StoreOutputRequest';

/**
 * Store multiple outputs request object.
 * @export
 * @interface StoreMultipleOutputsRequest
 */
export interface StoreMultipleOutputsRequest {
    /**
     * 
     * @type {Array<StoreOutputRequest>}
     * @memberof StoreMultipleOutputsRequest
     */
    data: Array<StoreOutputRequest>;
}

/**
 * Check if a given object implements the StoreMultipleOutputsRequest interface.
 */
export function instanceOfStoreMultipleOutputsRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function StoreMultipleOutputsRequestFromJSON(json: any): StoreMultipleOutputsRequest {
    return StoreMultipleOutputsRequestFromJSONTyped(json, false);
}

export function StoreMultipleOutputsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreMultipleOutputsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(StoreOutputRequestFromJSON)),
    };
}

export function StoreMultipleOutputsRequestToJSON(value?: StoreMultipleOutputsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(StoreOutputRequestToJSON)),
    };
}

