/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CovarBeta } from './CovarBeta';
import {
    CovarBetaFromJSON,
    CovarBetaFromJSONTyped,
    CovarBetaToJSON,
} from './CovarBeta';

/**
 * Store covar beta response object.
 * @export
 * @interface StoreCovarBetaResponse
 */
export interface StoreCovarBetaResponse {
    /**
     * 
     * @type {CovarBeta}
     * @memberof StoreCovarBetaResponse
     */
    data: CovarBeta;
    /**
     * 
     * @type {string}
     * @memberof StoreCovarBetaResponse
     */
    message: string;
}

/**
 * Check if a given object implements the StoreCovarBetaResponse interface.
 */
export function instanceOfStoreCovarBetaResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function StoreCovarBetaResponseFromJSON(json: any): StoreCovarBetaResponse {
    return StoreCovarBetaResponseFromJSONTyped(json, false);
}

export function StoreCovarBetaResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreCovarBetaResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': CovarBetaFromJSON(json['data']),
        'message': json['message'],
    };
}

export function StoreCovarBetaResponseToJSON(value?: StoreCovarBetaResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': CovarBetaToJSON(value.data),
        'message': value.message,
    };
}

