/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Request for updating an aircraft record.
 *            `name` must be unique within the `enum.aircrafts` table.
 * @export
 * @interface UpdateAircraftRequest
 */
export interface UpdateAircraftRequest {
    /**
     * 
     * @type {number}
     * @memberof UpdateAircraftRequest
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateAircraftRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the UpdateAircraftRequest interface.
 */
export function instanceOfUpdateAircraftRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function UpdateAircraftRequestFromJSON(json: any): UpdateAircraftRequest {
    return UpdateAircraftRequestFromJSONTyped(json, false);
}

export function UpdateAircraftRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAircraftRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function UpdateAircraftRequestToJSON(value?: UpdateAircraftRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}

