/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    AsyncMultipleKeyResponse,
    instanceOfAsyncMultipleKeyResponse,
    AsyncMultipleKeyResponseFromJSON,
    AsyncMultipleKeyResponseFromJSONTyped,
    AsyncMultipleKeyResponseToJSON,
} from './AsyncMultipleKeyResponse';
import {
    UpdateMultipleCovarCategoriesResponse,
    instanceOfUpdateMultipleCovarCategoriesResponse,
    UpdateMultipleCovarCategoriesResponseFromJSON,
    UpdateMultipleCovarCategoriesResponseFromJSONTyped,
    UpdateMultipleCovarCategoriesResponseToJSON,
} from './UpdateMultipleCovarCategoriesResponse';

/**
 * @type UpdateMultipleCovarCategories200Response
 * 
 * @export
 */
export type UpdateMultipleCovarCategories200Response = AsyncMultipleKeyResponse | UpdateMultipleCovarCategoriesResponse;

export function UpdateMultipleCovarCategories200ResponseFromJSON(json: any): UpdateMultipleCovarCategories200Response {
    return UpdateMultipleCovarCategories200ResponseFromJSONTyped(json, false);
}

export function UpdateMultipleCovarCategories200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMultipleCovarCategories200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...AsyncMultipleKeyResponseFromJSONTyped(json, true), ...UpdateMultipleCovarCategoriesResponseFromJSONTyped(json, true) };
}

export function UpdateMultipleCovarCategories200ResponseToJSON(value?: UpdateMultipleCovarCategories200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfAsyncMultipleKeyResponse(value)) {
        return AsyncMultipleKeyResponseToJSON(value as AsyncMultipleKeyResponse);
    }
    if (instanceOfUpdateMultipleCovarCategoriesResponse(value)) {
        return UpdateMultipleCovarCategoriesResponseToJSON(value as UpdateMultipleCovarCategoriesResponse);
    }

    return {};
}

