/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UpdateCountCategoryRequest } from './UpdateCountCategoryRequest';
import {
    UpdateCountCategoryRequestFromJSON,
    UpdateCountCategoryRequestFromJSONTyped,
    UpdateCountCategoryRequestToJSON,
} from './UpdateCountCategoryRequest';

/**
 * Update multiple count categories request object.
 * @export
 * @interface UpdateMultipleCountCategoriesRequest
 */
export interface UpdateMultipleCountCategoriesRequest {
    /**
     * 
     * @type {Array<UpdateCountCategoryRequest>}
     * @memberof UpdateMultipleCountCategoriesRequest
     */
    data: Array<UpdateCountCategoryRequest>;
}

/**
 * Check if a given object implements the UpdateMultipleCountCategoriesRequest interface.
 */
export function instanceOfUpdateMultipleCountCategoriesRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function UpdateMultipleCountCategoriesRequestFromJSON(json: any): UpdateMultipleCountCategoriesRequest {
    return UpdateMultipleCountCategoriesRequestFromJSONTyped(json, false);
}

export function UpdateMultipleCountCategoriesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMultipleCountCategoriesRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(UpdateCountCategoryRequestFromJSON)),
    };
}

export function UpdateMultipleCountCategoriesRequestToJSON(value?: UpdateMultipleCountCategoriesRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(UpdateCountCategoryRequestToJSON)),
    };
}

