/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UpdateMultipleIpmEntriesResponseItem } from './UpdateMultipleIpmEntriesResponseItem';
import {
    UpdateMultipleIpmEntriesResponseItemFromJSON,
    UpdateMultipleIpmEntriesResponseItemFromJSONTyped,
    UpdateMultipleIpmEntriesResponseItemToJSON,
} from './UpdateMultipleIpmEntriesResponseItem';

/**
 * Update multiple IPM entries response object.
 * @export
 * @interface UpdateMultipleIpmEntriesResponse
 */
export interface UpdateMultipleIpmEntriesResponse {
    /**
     * 
     * @type {Array<UpdateMultipleIpmEntriesResponseItem>}
     * @memberof UpdateMultipleIpmEntriesResponse
     */
    data: Array<UpdateMultipleIpmEntriesResponseItem>;
    /**
     * 
     * @type {string}
     * @memberof UpdateMultipleIpmEntriesResponse
     */
    message: string;
}

/**
 * Check if a given object implements the UpdateMultipleIpmEntriesResponse interface.
 */
export function instanceOfUpdateMultipleIpmEntriesResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function UpdateMultipleIpmEntriesResponseFromJSON(json: any): UpdateMultipleIpmEntriesResponse {
    return UpdateMultipleIpmEntriesResponseFromJSONTyped(json, false);
}

export function UpdateMultipleIpmEntriesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMultipleIpmEntriesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(UpdateMultipleIpmEntriesResponseItemFromJSON)),
        'message': json['message'],
    };
}

export function UpdateMultipleIpmEntriesResponseToJSON(value?: UpdateMultipleIpmEntriesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(UpdateMultipleIpmEntriesResponseItemToJSON)),
        'message': value.message,
    };
}

