/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    AsyncMultipleKeyResponse,
    instanceOfAsyncMultipleKeyResponse,
    AsyncMultipleKeyResponseFromJSON,
    AsyncMultipleKeyResponseFromJSONTyped,
    AsyncMultipleKeyResponseToJSON,
} from './AsyncMultipleKeyResponse';
import {
    UpdateMultipleAerialSurveyDesignsResponse,
    instanceOfUpdateMultipleAerialSurveyDesignsResponse,
    UpdateMultipleAerialSurveyDesignsResponseFromJSON,
    UpdateMultipleAerialSurveyDesignsResponseFromJSONTyped,
    UpdateMultipleAerialSurveyDesignsResponseToJSON,
} from './UpdateMultipleAerialSurveyDesignsResponse';

/**
 * @type UpdateMultipleAerialSurveyDesigns200Response
 * 
 * @export
 */
export type UpdateMultipleAerialSurveyDesigns200Response = AsyncMultipleKeyResponse | UpdateMultipleAerialSurveyDesignsResponse;

export function UpdateMultipleAerialSurveyDesigns200ResponseFromJSON(json: any): UpdateMultipleAerialSurveyDesigns200Response {
    return UpdateMultipleAerialSurveyDesigns200ResponseFromJSONTyped(json, false);
}

export function UpdateMultipleAerialSurveyDesigns200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMultipleAerialSurveyDesigns200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...AsyncMultipleKeyResponseFromJSONTyped(json, true), ...UpdateMultipleAerialSurveyDesignsResponseFromJSONTyped(json, true) };
}

export function UpdateMultipleAerialSurveyDesigns200ResponseToJSON(value?: UpdateMultipleAerialSurveyDesigns200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfAsyncMultipleKeyResponse(value)) {
        return AsyncMultipleKeyResponseToJSON(value as AsyncMultipleKeyResponse);
    }
    if (instanceOfUpdateMultipleAerialSurveyDesignsResponse(value)) {
        return UpdateMultipleAerialSurveyDesignsResponseToJSON(value as UpdateMultipleAerialSurveyDesignsResponse);
    }

    return {};
}

