/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UpdateMultipleRegionsResponseItemData } from './UpdateMultipleRegionsResponseItemData';
import {
    UpdateMultipleRegionsResponseItemDataFromJSON,
    UpdateMultipleRegionsResponseItemDataFromJSONTyped,
    UpdateMultipleRegionsResponseItemDataToJSON,
} from './UpdateMultipleRegionsResponseItemData';

/**
 * Update multiple regions response item object.
 * @export
 * @interface UpdateMultipleRegionsResponseItem
 */
export interface UpdateMultipleRegionsResponseItem {
    /**
     * 
     * @type {UpdateMultipleRegionsResponseItemData}
     * @memberof UpdateMultipleRegionsResponseItem
     */
    data: UpdateMultipleRegionsResponseItemData;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateMultipleRegionsResponseItem
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof UpdateMultipleRegionsResponseItem
     */
    message: string;
    /**
     * 
     * @type {object}
     * @memberof UpdateMultipleRegionsResponseItem
     */
    errors?: object;
}

/**
 * Check if a given object implements the UpdateMultipleRegionsResponseItem interface.
 */
export function instanceOfUpdateMultipleRegionsResponseItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "success" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function UpdateMultipleRegionsResponseItemFromJSON(json: any): UpdateMultipleRegionsResponseItem {
    return UpdateMultipleRegionsResponseItemFromJSONTyped(json, false);
}

export function UpdateMultipleRegionsResponseItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMultipleRegionsResponseItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': UpdateMultipleRegionsResponseItemDataFromJSON(json['data']),
        'success': json['success'],
        'message': json['message'],
        'errors': !exists(json, 'errors') ? undefined : json['errors'],
    };
}

export function UpdateMultipleRegionsResponseItemToJSON(value?: UpdateMultipleRegionsResponseItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': UpdateMultipleRegionsResponseItemDataToJSON(value.data),
        'success': value.success,
        'message': value.message,
        'errors': value.errors,
    };
}

