/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UpdateMultipleEntryColumnMappingsResponseItemData } from './UpdateMultipleEntryColumnMappingsResponseItemData';
import {
    UpdateMultipleEntryColumnMappingsResponseItemDataFromJSON,
    UpdateMultipleEntryColumnMappingsResponseItemDataFromJSONTyped,
    UpdateMultipleEntryColumnMappingsResponseItemDataToJSON,
} from './UpdateMultipleEntryColumnMappingsResponseItemData';

/**
 * Update multiple entry column mappings response item object.
 * @export
 * @interface UpdateMultipleEntryColumnMappingsResponseItem
 */
export interface UpdateMultipleEntryColumnMappingsResponseItem {
    /**
     * 
     * @type {UpdateMultipleEntryColumnMappingsResponseItemData}
     * @memberof UpdateMultipleEntryColumnMappingsResponseItem
     */
    data: UpdateMultipleEntryColumnMappingsResponseItemData;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateMultipleEntryColumnMappingsResponseItem
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof UpdateMultipleEntryColumnMappingsResponseItem
     */
    message: string;
    /**
     * 
     * @type {object}
     * @memberof UpdateMultipleEntryColumnMappingsResponseItem
     */
    errors?: object;
}

/**
 * Check if a given object implements the UpdateMultipleEntryColumnMappingsResponseItem interface.
 */
export function instanceOfUpdateMultipleEntryColumnMappingsResponseItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "success" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function UpdateMultipleEntryColumnMappingsResponseItemFromJSON(json: any): UpdateMultipleEntryColumnMappingsResponseItem {
    return UpdateMultipleEntryColumnMappingsResponseItemFromJSONTyped(json, false);
}

export function UpdateMultipleEntryColumnMappingsResponseItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMultipleEntryColumnMappingsResponseItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': UpdateMultipleEntryColumnMappingsResponseItemDataFromJSON(json['data']),
        'success': json['success'],
        'message': json['message'],
        'errors': !exists(json, 'errors') ? undefined : json['errors'],
    };
}

export function UpdateMultipleEntryColumnMappingsResponseItemToJSON(value?: UpdateMultipleEntryColumnMappingsResponseItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': UpdateMultipleEntryColumnMappingsResponseItemDataToJSON(value.data),
        'success': value.success,
        'message': value.message,
        'errors': value.errors,
    };
}

