/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UpdateMultipleStrataResponseItemData } from './UpdateMultipleStrataResponseItemData';
import {
    UpdateMultipleStrataResponseItemDataFromJSON,
    UpdateMultipleStrataResponseItemDataFromJSONTyped,
    UpdateMultipleStrataResponseItemDataToJSON,
} from './UpdateMultipleStrataResponseItemData';

/**
 * Update multiple strata response item object.
 * @export
 * @interface UpdateMultipleStrataResponseItem
 */
export interface UpdateMultipleStrataResponseItem {
    /**
     * 
     * @type {UpdateMultipleStrataResponseItemData}
     * @memberof UpdateMultipleStrataResponseItem
     */
    data: UpdateMultipleStrataResponseItemData;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateMultipleStrataResponseItem
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof UpdateMultipleStrataResponseItem
     */
    message: string;
    /**
     * 
     * @type {object}
     * @memberof UpdateMultipleStrataResponseItem
     */
    errors?: object;
}

/**
 * Check if a given object implements the UpdateMultipleStrataResponseItem interface.
 */
export function instanceOfUpdateMultipleStrataResponseItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "success" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function UpdateMultipleStrataResponseItemFromJSON(json: any): UpdateMultipleStrataResponseItem {
    return UpdateMultipleStrataResponseItemFromJSONTyped(json, false);
}

export function UpdateMultipleStrataResponseItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMultipleStrataResponseItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': UpdateMultipleStrataResponseItemDataFromJSON(json['data']),
        'success': json['success'],
        'message': json['message'],
        'errors': !exists(json, 'errors') ? undefined : json['errors'],
    };
}

export function UpdateMultipleStrataResponseItemToJSON(value?: UpdateMultipleStrataResponseItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': UpdateMultipleStrataResponseItemDataToJSON(value.data),
        'success': value.success,
        'message': value.message,
        'errors': value.errors,
    };
}

