/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    AerialSurveyDesign,
    instanceOfAerialSurveyDesign,
    AerialSurveyDesignFromJSON,
    AerialSurveyDesignFromJSONTyped,
    AerialSurveyDesignToJSON,
} from './AerialSurveyDesign';
import {
    UpdateAerialSurveyDesignRequest,
    instanceOfUpdateAerialSurveyDesignRequest,
    UpdateAerialSurveyDesignRequestFromJSON,
    UpdateAerialSurveyDesignRequestFromJSONTyped,
    UpdateAerialSurveyDesignRequestToJSON,
} from './UpdateAerialSurveyDesignRequest';

/**
 * @type UpdateMultipleAerialSurveyDesignsResponseItemData
 * 
 * @export
 */
export type UpdateMultipleAerialSurveyDesignsResponseItemData = AerialSurveyDesign | UpdateAerialSurveyDesignRequest;

export function UpdateMultipleAerialSurveyDesignsResponseItemDataFromJSON(json: any): UpdateMultipleAerialSurveyDesignsResponseItemData {
    return UpdateMultipleAerialSurveyDesignsResponseItemDataFromJSONTyped(json, false);
}

export function UpdateMultipleAerialSurveyDesignsResponseItemDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMultipleAerialSurveyDesignsResponseItemData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...AerialSurveyDesignFromJSONTyped(json, true), ...UpdateAerialSurveyDesignRequestFromJSONTyped(json, true) };
}

export function UpdateMultipleAerialSurveyDesignsResponseItemDataToJSON(value?: UpdateMultipleAerialSurveyDesignsResponseItemData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfAerialSurveyDesign(value)) {
        return AerialSurveyDesignToJSON(value as AerialSurveyDesign);
    }
    if (instanceOfUpdateAerialSurveyDesignRequest(value)) {
        return UpdateAerialSurveyDesignRequestToJSON(value as UpdateAerialSurveyDesignRequest);
    }

    return {};
}

