/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UpdateMultipleSubunitsResponseItemData } from './UpdateMultipleSubunitsResponseItemData';
import {
    UpdateMultipleSubunitsResponseItemDataFromJSON,
    UpdateMultipleSubunitsResponseItemDataFromJSONTyped,
    UpdateMultipleSubunitsResponseItemDataToJSON,
} from './UpdateMultipleSubunitsResponseItemData';

/**
 * Update multiple subunits response item object.
 * @export
 * @interface UpdateMultipleSubunitsResponseItem
 */
export interface UpdateMultipleSubunitsResponseItem {
    /**
     * 
     * @type {UpdateMultipleSubunitsResponseItemData}
     * @memberof UpdateMultipleSubunitsResponseItem
     */
    data: UpdateMultipleSubunitsResponseItemData;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateMultipleSubunitsResponseItem
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof UpdateMultipleSubunitsResponseItem
     */
    message: string;
    /**
     * 
     * @type {object}
     * @memberof UpdateMultipleSubunitsResponseItem
     */
    errors?: object;
}

/**
 * Check if a given object implements the UpdateMultipleSubunitsResponseItem interface.
 */
export function instanceOfUpdateMultipleSubunitsResponseItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "success" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function UpdateMultipleSubunitsResponseItemFromJSON(json: any): UpdateMultipleSubunitsResponseItem {
    return UpdateMultipleSubunitsResponseItemFromJSONTyped(json, false);
}

export function UpdateMultipleSubunitsResponseItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMultipleSubunitsResponseItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': UpdateMultipleSubunitsResponseItemDataFromJSON(json['data']),
        'success': json['success'],
        'message': json['message'],
        'errors': !exists(json, 'errors') ? undefined : json['errors'],
    };
}

export function UpdateMultipleSubunitsResponseItemToJSON(value?: UpdateMultipleSubunitsResponseItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': UpdateMultipleSubunitsResponseItemDataToJSON(value.data),
        'success': value.success,
        'message': value.message,
        'errors': value.errors,
    };
}

