/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UpdateMultipleModelsResponseItemData } from './UpdateMultipleModelsResponseItemData';
import {
    UpdateMultipleModelsResponseItemDataFromJSON,
    UpdateMultipleModelsResponseItemDataFromJSONTyped,
    UpdateMultipleModelsResponseItemDataToJSON,
} from './UpdateMultipleModelsResponseItemData';

/**
 * Update multiple models response item object.
 * @export
 * @interface UpdateMultipleModelsResponseItem
 */
export interface UpdateMultipleModelsResponseItem {
    /**
     * 
     * @type {UpdateMultipleModelsResponseItemData}
     * @memberof UpdateMultipleModelsResponseItem
     */
    data: UpdateMultipleModelsResponseItemData;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateMultipleModelsResponseItem
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof UpdateMultipleModelsResponseItem
     */
    message: string;
    /**
     * 
     * @type {object}
     * @memberof UpdateMultipleModelsResponseItem
     */
    errors?: object;
}

/**
 * Check if a given object implements the UpdateMultipleModelsResponseItem interface.
 */
export function instanceOfUpdateMultipleModelsResponseItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "success" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function UpdateMultipleModelsResponseItemFromJSON(json: any): UpdateMultipleModelsResponseItem {
    return UpdateMultipleModelsResponseItemFromJSONTyped(json, false);
}

export function UpdateMultipleModelsResponseItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMultipleModelsResponseItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': UpdateMultipleModelsResponseItemDataFromJSON(json['data']),
        'success': json['success'],
        'message': json['message'],
        'errors': !exists(json, 'errors') ? undefined : json['errors'],
    };
}

export function UpdateMultipleModelsResponseItemToJSON(value?: UpdateMultipleModelsResponseItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': UpdateMultipleModelsResponseItemDataToJSON(value.data),
        'success': value.success,
        'message': value.message,
        'errors': value.errors,
    };
}

