/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    AsyncMultipleKeyResponse,
    instanceOfAsyncMultipleKeyResponse,
    AsyncMultipleKeyResponseFromJSON,
    AsyncMultipleKeyResponseFromJSONTyped,
    AsyncMultipleKeyResponseToJSON,
} from './AsyncMultipleKeyResponse';
import {
    UpdateMultipleCovarBetasResponse,
    instanceOfUpdateMultipleCovarBetasResponse,
    UpdateMultipleCovarBetasResponseFromJSON,
    UpdateMultipleCovarBetasResponseFromJSONTyped,
    UpdateMultipleCovarBetasResponseToJSON,
} from './UpdateMultipleCovarBetasResponse';

/**
 * @type UpdateMultipleCovarBetas200Response
 * 
 * @export
 */
export type UpdateMultipleCovarBetas200Response = AsyncMultipleKeyResponse | UpdateMultipleCovarBetasResponse;

export function UpdateMultipleCovarBetas200ResponseFromJSON(json: any): UpdateMultipleCovarBetas200Response {
    return UpdateMultipleCovarBetas200ResponseFromJSONTyped(json, false);
}

export function UpdateMultipleCovarBetas200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMultipleCovarBetas200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...AsyncMultipleKeyResponseFromJSONTyped(json, true), ...UpdateMultipleCovarBetasResponseFromJSONTyped(json, true) };
}

export function UpdateMultipleCovarBetas200ResponseToJSON(value?: UpdateMultipleCovarBetas200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfAsyncMultipleKeyResponse(value)) {
        return AsyncMultipleKeyResponseToJSON(value as AsyncMultipleKeyResponse);
    }
    if (instanceOfUpdateMultipleCovarBetasResponse(value)) {
        return UpdateMultipleCovarBetasResponseToJSON(value as UpdateMultipleCovarBetasResponse);
    }

    return {};
}

