/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UpdateOutputStepRequest } from './UpdateOutputStepRequest';
import {
    UpdateOutputStepRequestFromJSON,
    UpdateOutputStepRequestFromJSONTyped,
    UpdateOutputStepRequestToJSON,
} from './UpdateOutputStepRequest';

/**
 * Update multiple outputs request object.
 * @export
 * @interface UpdateMultipleOutputStepsRequest
 */
export interface UpdateMultipleOutputStepsRequest {
    /**
     * 
     * @type {Array<UpdateOutputStepRequest>}
     * @memberof UpdateMultipleOutputStepsRequest
     */
    data: Array<UpdateOutputStepRequest>;
}

/**
 * Check if a given object implements the UpdateMultipleOutputStepsRequest interface.
 */
export function instanceOfUpdateMultipleOutputStepsRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function UpdateMultipleOutputStepsRequestFromJSON(json: any): UpdateMultipleOutputStepsRequest {
    return UpdateMultipleOutputStepsRequestFromJSONTyped(json, false);
}

export function UpdateMultipleOutputStepsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMultipleOutputStepsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(UpdateOutputStepRequestFromJSON)),
    };
}

export function UpdateMultipleOutputStepsRequestToJSON(value?: UpdateMultipleOutputStepsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(UpdateOutputStepRequestToJSON)),
    };
}

