/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UpdateSurveyTypeRequest } from './UpdateSurveyTypeRequest';
import {
    UpdateSurveyTypeRequestFromJSON,
    UpdateSurveyTypeRequestFromJSONTyped,
    UpdateSurveyTypeRequestToJSON,
} from './UpdateSurveyTypeRequest';

/**
 * Update multiple species request object.
 * @export
 * @interface UpdateMultipleSurveyTypesRequest
 */
export interface UpdateMultipleSurveyTypesRequest {
    /**
     * 
     * @type {Array<UpdateSurveyTypeRequest>}
     * @memberof UpdateMultipleSurveyTypesRequest
     */
    data: Array<UpdateSurveyTypeRequest>;
}

/**
 * Check if a given object implements the UpdateMultipleSurveyTypesRequest interface.
 */
export function instanceOfUpdateMultipleSurveyTypesRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function UpdateMultipleSurveyTypesRequestFromJSON(json: any): UpdateMultipleSurveyTypesRequest {
    return UpdateMultipleSurveyTypesRequestFromJSONTyped(json, false);
}

export function UpdateMultipleSurveyTypesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMultipleSurveyTypesRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(UpdateSurveyTypeRequestFromJSON)),
    };
}

export function UpdateMultipleSurveyTypesRequestToJSON(value?: UpdateMultipleSurveyTypesRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(UpdateSurveyTypeRequestToJSON)),
    };
}

