/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    AsyncMultipleKeyResponse,
    instanceOfAsyncMultipleKeyResponse,
    AsyncMultipleKeyResponseFromJSON,
    AsyncMultipleKeyResponseFromJSONTyped,
    AsyncMultipleKeyResponseToJSON,
} from './AsyncMultipleKeyResponse';
import {
    UpdateMultipleModelsResponse,
    instanceOfUpdateMultipleModelsResponse,
    UpdateMultipleModelsResponseFromJSON,
    UpdateMultipleModelsResponseFromJSONTyped,
    UpdateMultipleModelsResponseToJSON,
} from './UpdateMultipleModelsResponse';

/**
 * @type UpdateMultipleModels200Response
 * 
 * @export
 */
export type UpdateMultipleModels200Response = AsyncMultipleKeyResponse | UpdateMultipleModelsResponse;

export function UpdateMultipleModels200ResponseFromJSON(json: any): UpdateMultipleModels200Response {
    return UpdateMultipleModels200ResponseFromJSONTyped(json, false);
}

export function UpdateMultipleModels200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMultipleModels200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...AsyncMultipleKeyResponseFromJSONTyped(json, true), ...UpdateMultipleModelsResponseFromJSONTyped(json, true) };
}

export function UpdateMultipleModels200ResponseToJSON(value?: UpdateMultipleModels200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfAsyncMultipleKeyResponse(value)) {
        return AsyncMultipleKeyResponseToJSON(value as AsyncMultipleKeyResponse);
    }
    if (instanceOfUpdateMultipleModelsResponse(value)) {
        return UpdateMultipleModelsResponseToJSON(value as UpdateMultipleModelsResponse);
    }

    return {};
}

