/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UpdateMultipleCovarBetasResponseItem } from './UpdateMultipleCovarBetasResponseItem';
import {
    UpdateMultipleCovarBetasResponseItemFromJSON,
    UpdateMultipleCovarBetasResponseItemFromJSONTyped,
    UpdateMultipleCovarBetasResponseItemToJSON,
} from './UpdateMultipleCovarBetasResponseItem';

/**
 * Update multiple covar betas response object.
 * @export
 * @interface UpdateMultipleCovarBetasResponse
 */
export interface UpdateMultipleCovarBetasResponse {
    /**
     * 
     * @type {Array<UpdateMultipleCovarBetasResponseItem>}
     * @memberof UpdateMultipleCovarBetasResponse
     */
    data: Array<UpdateMultipleCovarBetasResponseItem>;
    /**
     * 
     * @type {string}
     * @memberof UpdateMultipleCovarBetasResponse
     */
    message: string;
}

/**
 * Check if a given object implements the UpdateMultipleCovarBetasResponse interface.
 */
export function instanceOfUpdateMultipleCovarBetasResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function UpdateMultipleCovarBetasResponseFromJSON(json: any): UpdateMultipleCovarBetasResponse {
    return UpdateMultipleCovarBetasResponseFromJSONTyped(json, false);
}

export function UpdateMultipleCovarBetasResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMultipleCovarBetasResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(UpdateMultipleCovarBetasResponseItemFromJSON)),
        'message': json['message'],
    };
}

export function UpdateMultipleCovarBetasResponseToJSON(value?: UpdateMultipleCovarBetasResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(UpdateMultipleCovarBetasResponseItemToJSON)),
        'message': value.message,
    };
}

