/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    AsyncMultipleKeyResponse,
    instanceOfAsyncMultipleKeyResponse,
    AsyncMultipleKeyResponseFromJSON,
    AsyncMultipleKeyResponseFromJSONTyped,
    AsyncMultipleKeyResponseToJSON,
} from './AsyncMultipleKeyResponse';
import {
    UpdateMultiplePriorEntriesResponse,
    instanceOfUpdateMultiplePriorEntriesResponse,
    UpdateMultiplePriorEntriesResponseFromJSON,
    UpdateMultiplePriorEntriesResponseFromJSONTyped,
    UpdateMultiplePriorEntriesResponseToJSON,
} from './UpdateMultiplePriorEntriesResponse';

/**
 * @type UpdateMultiplePriorEntries200Response
 * 
 * @export
 */
export type UpdateMultiplePriorEntries200Response = AsyncMultipleKeyResponse | UpdateMultiplePriorEntriesResponse;

export function UpdateMultiplePriorEntries200ResponseFromJSON(json: any): UpdateMultiplePriorEntries200Response {
    return UpdateMultiplePriorEntries200ResponseFromJSONTyped(json, false);
}

export function UpdateMultiplePriorEntries200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMultiplePriorEntries200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...AsyncMultipleKeyResponseFromJSONTyped(json, true), ...UpdateMultiplePriorEntriesResponseFromJSONTyped(json, true) };
}

export function UpdateMultiplePriorEntries200ResponseToJSON(value?: UpdateMultiplePriorEntries200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfAsyncMultipleKeyResponse(value)) {
        return AsyncMultipleKeyResponseToJSON(value as AsyncMultipleKeyResponse);
    }
    if (instanceOfUpdateMultiplePriorEntriesResponse(value)) {
        return UpdateMultiplePriorEntriesResponseToJSON(value as UpdateMultiplePriorEntriesResponse);
    }

    return {};
}

