/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Output } from './Output';
import {
    OutputFromJSON,
    OutputFromJSONTyped,
    OutputToJSON,
} from './Output';

/**
 * Update model output response object.
 * @export
 * @interface UpdateOutputResponse
 */
export interface UpdateOutputResponse {
    /**
     * 
     * @type {Output}
     * @memberof UpdateOutputResponse
     */
    data: Output;
    /**
     * 
     * @type {string}
     * @memberof UpdateOutputResponse
     */
    message: string;
}

/**
 * Check if a given object implements the UpdateOutputResponse interface.
 */
export function instanceOfUpdateOutputResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function UpdateOutputResponseFromJSON(json: any): UpdateOutputResponse {
    return UpdateOutputResponseFromJSONTyped(json, false);
}

export function UpdateOutputResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateOutputResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': OutputFromJSON(json['data']),
        'message': json['message'],
    };
}

export function UpdateOutputResponseToJSON(value?: UpdateOutputResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': OutputToJSON(value.data),
        'message': value.message,
    };
}

