/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UpdateMultipleSurveyTypesResponseItemData } from './UpdateMultipleSurveyTypesResponseItemData';
import {
    UpdateMultipleSurveyTypesResponseItemDataFromJSON,
    UpdateMultipleSurveyTypesResponseItemDataFromJSONTyped,
    UpdateMultipleSurveyTypesResponseItemDataToJSON,
} from './UpdateMultipleSurveyTypesResponseItemData';

/**
 * Update multiple species response item object.
 * @export
 * @interface UpdateMultipleSurveyTypesResponseItem
 */
export interface UpdateMultipleSurveyTypesResponseItem {
    /**
     * 
     * @type {UpdateMultipleSurveyTypesResponseItemData}
     * @memberof UpdateMultipleSurveyTypesResponseItem
     */
    data: UpdateMultipleSurveyTypesResponseItemData;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateMultipleSurveyTypesResponseItem
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof UpdateMultipleSurveyTypesResponseItem
     */
    message: string;
    /**
     * 
     * @type {object}
     * @memberof UpdateMultipleSurveyTypesResponseItem
     */
    errors?: object;
}

/**
 * Check if a given object implements the UpdateMultipleSurveyTypesResponseItem interface.
 */
export function instanceOfUpdateMultipleSurveyTypesResponseItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "success" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function UpdateMultipleSurveyTypesResponseItemFromJSON(json: any): UpdateMultipleSurveyTypesResponseItem {
    return UpdateMultipleSurveyTypesResponseItemFromJSONTyped(json, false);
}

export function UpdateMultipleSurveyTypesResponseItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMultipleSurveyTypesResponseItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': UpdateMultipleSurveyTypesResponseItemDataFromJSON(json['data']),
        'success': json['success'],
        'message': json['message'],
        'errors': !exists(json, 'errors') ? undefined : json['errors'],
    };
}

export function UpdateMultipleSurveyTypesResponseItemToJSON(value?: UpdateMultipleSurveyTypesResponseItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': UpdateMultipleSurveyTypesResponseItemDataToJSON(value.data),
        'success': value.success,
        'message': value.message,
        'errors': value.errors,
    };
}

