/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UpdateAerialSurveyDesignRequest } from './UpdateAerialSurveyDesignRequest';
import {
    UpdateAerialSurveyDesignRequestFromJSON,
    UpdateAerialSurveyDesignRequestFromJSONTyped,
    UpdateAerialSurveyDesignRequestToJSON,
} from './UpdateAerialSurveyDesignRequest';

/**
 * Update multiple aerial survey designs request object.
 * @export
 * @interface UpdateMultipleAerialSurveyDesignsRequest
 */
export interface UpdateMultipleAerialSurveyDesignsRequest {
    /**
     * 
     * @type {Array<UpdateAerialSurveyDesignRequest>}
     * @memberof UpdateMultipleAerialSurveyDesignsRequest
     */
    data: Array<UpdateAerialSurveyDesignRequest>;
}

/**
 * Check if a given object implements the UpdateMultipleAerialSurveyDesignsRequest interface.
 */
export function instanceOfUpdateMultipleAerialSurveyDesignsRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function UpdateMultipleAerialSurveyDesignsRequestFromJSON(json: any): UpdateMultipleAerialSurveyDesignsRequest {
    return UpdateMultipleAerialSurveyDesignsRequestFromJSONTyped(json, false);
}

export function UpdateMultipleAerialSurveyDesignsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMultipleAerialSurveyDesignsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(UpdateAerialSurveyDesignRequestFromJSON)),
    };
}

export function UpdateMultipleAerialSurveyDesignsRequestToJSON(value?: UpdateMultipleAerialSurveyDesignsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(UpdateAerialSurveyDesignRequestToJSON)),
    };
}

