/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    OutputStep,
    instanceOfOutputStep,
    OutputStepFromJSON,
    OutputStepFromJSONTyped,
    OutputStepToJSON,
} from './OutputStep';
import {
    UpdateOutputStepRequest,
    instanceOfUpdateOutputStepRequest,
    UpdateOutputStepRequestFromJSON,
    UpdateOutputStepRequestFromJSONTyped,
    UpdateOutputStepRequestToJSON,
} from './UpdateOutputStepRequest';

/**
 * @type UpdateMultipleOutputStepsResponseItemData
 * 
 * @export
 */
export type UpdateMultipleOutputStepsResponseItemData = OutputStep | UpdateOutputStepRequest;

export function UpdateMultipleOutputStepsResponseItemDataFromJSON(json: any): UpdateMultipleOutputStepsResponseItemData {
    return UpdateMultipleOutputStepsResponseItemDataFromJSONTyped(json, false);
}

export function UpdateMultipleOutputStepsResponseItemDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMultipleOutputStepsResponseItemData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...OutputStepFromJSONTyped(json, true), ...UpdateOutputStepRequestFromJSONTyped(json, true) };
}

export function UpdateMultipleOutputStepsResponseItemDataToJSON(value?: UpdateMultipleOutputStepsResponseItemData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfOutputStep(value)) {
        return OutputStepToJSON(value as OutputStep);
    }
    if (instanceOfUpdateOutputStepRequest(value)) {
        return UpdateOutputStepRequestToJSON(value as UpdateOutputStepRequest);
    }

    return {};
}

