/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Request for updating a covar bin record.
 * @export
 * @interface UpdateCovarBinRequest
 */
export interface UpdateCovarBinRequest {
    /**
     * 
     * @type {number}
     * @memberof UpdateCovarBinRequest
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateCovarBinRequest
     */
    covarId?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateCovarBinRequest
     */
    min?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateCovarBinRequest
     */
    max?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateCovarBinRequest
     */
    value?: number;
}

/**
 * Check if a given object implements the UpdateCovarBinRequest interface.
 */
export function instanceOfUpdateCovarBinRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function UpdateCovarBinRequestFromJSON(json: any): UpdateCovarBinRequest {
    return UpdateCovarBinRequestFromJSONTyped(json, false);
}

export function UpdateCovarBinRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCovarBinRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'covarId': !exists(json, 'covar_id') ? undefined : json['covar_id'],
        'min': !exists(json, 'min') ? undefined : json['min'],
        'max': !exists(json, 'max') ? undefined : json['max'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function UpdateCovarBinRequestToJSON(value?: UpdateCovarBinRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'covar_id': value.covarId,
        'min': value.min,
        'max': value.max,
        'value': value.value,
    };
}

