/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OutputStep } from './OutputStep';
import {
    OutputStepFromJSON,
    OutputStepFromJSONTyped,
    OutputStepToJSON,
} from './OutputStep';

/**
 * Update model output step response object.
 * @export
 * @interface UpdateOutputStepResponse
 */
export interface UpdateOutputStepResponse {
    /**
     * 
     * @type {OutputStep}
     * @memberof UpdateOutputStepResponse
     */
    data: OutputStep;
    /**
     * 
     * @type {string}
     * @memberof UpdateOutputStepResponse
     */
    message: string;
}

/**
 * Check if a given object implements the UpdateOutputStepResponse interface.
 */
export function instanceOfUpdateOutputStepResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function UpdateOutputStepResponseFromJSON(json: any): UpdateOutputStepResponse {
    return UpdateOutputStepResponseFromJSONTyped(json, false);
}

export function UpdateOutputStepResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateOutputStepResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': OutputStepFromJSON(json['data']),
        'message': json['message'],
    };
}

export function UpdateOutputStepResponseToJSON(value?: UpdateOutputStepResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': OutputStepToJSON(value.data),
        'message': value.message,
    };
}

