/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UpdateMultipleProjectSpeciesResponseItemData } from './UpdateMultipleProjectSpeciesResponseItemData';
import {
    UpdateMultipleProjectSpeciesResponseItemDataFromJSON,
    UpdateMultipleProjectSpeciesResponseItemDataFromJSONTyped,
    UpdateMultipleProjectSpeciesResponseItemDataToJSON,
} from './UpdateMultipleProjectSpeciesResponseItemData';

/**
 * Update multiple project species response item object.
 * @export
 * @interface UpdateMultipleProjectSpeciesResponseItem
 */
export interface UpdateMultipleProjectSpeciesResponseItem {
    /**
     * 
     * @type {UpdateMultipleProjectSpeciesResponseItemData}
     * @memberof UpdateMultipleProjectSpeciesResponseItem
     */
    data: UpdateMultipleProjectSpeciesResponseItemData;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateMultipleProjectSpeciesResponseItem
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof UpdateMultipleProjectSpeciesResponseItem
     */
    message: string;
    /**
     * 
     * @type {object}
     * @memberof UpdateMultipleProjectSpeciesResponseItem
     */
    errors?: object;
}

/**
 * Check if a given object implements the UpdateMultipleProjectSpeciesResponseItem interface.
 */
export function instanceOfUpdateMultipleProjectSpeciesResponseItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "success" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function UpdateMultipleProjectSpeciesResponseItemFromJSON(json: any): UpdateMultipleProjectSpeciesResponseItem {
    return UpdateMultipleProjectSpeciesResponseItemFromJSONTyped(json, false);
}

export function UpdateMultipleProjectSpeciesResponseItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMultipleProjectSpeciesResponseItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': UpdateMultipleProjectSpeciesResponseItemDataFromJSON(json['data']),
        'success': json['success'],
        'message': json['message'],
        'errors': !exists(json, 'errors') ? undefined : json['errors'],
    };
}

export function UpdateMultipleProjectSpeciesResponseItemToJSON(value?: UpdateMultipleProjectSpeciesResponseItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': UpdateMultipleProjectSpeciesResponseItemDataToJSON(value.data),
        'success': value.success,
        'message': value.message,
        'errors': value.errors,
    };
}

