/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    CountCategory,
    instanceOfCountCategory,
    CountCategoryFromJSON,
    CountCategoryFromJSONTyped,
    CountCategoryToJSON,
} from './CountCategory';
import {
    UpdateCountCategoryRequest,
    instanceOfUpdateCountCategoryRequest,
    UpdateCountCategoryRequestFromJSON,
    UpdateCountCategoryRequestFromJSONTyped,
    UpdateCountCategoryRequestToJSON,
} from './UpdateCountCategoryRequest';

/**
 * @type UpdateMultipleCountCategoriesResponseItemData
 * 
 * @export
 */
export type UpdateMultipleCountCategoriesResponseItemData = CountCategory | UpdateCountCategoryRequest;

export function UpdateMultipleCountCategoriesResponseItemDataFromJSON(json: any): UpdateMultipleCountCategoriesResponseItemData {
    return UpdateMultipleCountCategoriesResponseItemDataFromJSONTyped(json, false);
}

export function UpdateMultipleCountCategoriesResponseItemDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMultipleCountCategoriesResponseItemData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...CountCategoryFromJSONTyped(json, true), ...UpdateCountCategoryRequestFromJSONTyped(json, true) };
}

export function UpdateMultipleCountCategoriesResponseItemDataToJSON(value?: UpdateMultipleCountCategoriesResponseItemData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfCountCategory(value)) {
        return CountCategoryToJSON(value as CountCategory);
    }
    if (instanceOfUpdateCountCategoryRequest(value)) {
        return UpdateCountCategoryRequestToJSON(value as UpdateCountCategoryRequest);
    }

    return {};
}

