/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    CovarCategory,
    instanceOfCovarCategory,
    CovarCategoryFromJSON,
    CovarCategoryFromJSONTyped,
    CovarCategoryToJSON,
} from './CovarCategory';
import {
    UpdateCovarCategoryRequest,
    instanceOfUpdateCovarCategoryRequest,
    UpdateCovarCategoryRequestFromJSON,
    UpdateCovarCategoryRequestFromJSONTyped,
    UpdateCovarCategoryRequestToJSON,
} from './UpdateCovarCategoryRequest';

/**
 * @type UpdateMultipleCovarCategoriesResponseItemData
 * 
 * @export
 */
export type UpdateMultipleCovarCategoriesResponseItemData = CovarCategory | UpdateCovarCategoryRequest;

export function UpdateMultipleCovarCategoriesResponseItemDataFromJSON(json: any): UpdateMultipleCovarCategoriesResponseItemData {
    return UpdateMultipleCovarCategoriesResponseItemDataFromJSONTyped(json, false);
}

export function UpdateMultipleCovarCategoriesResponseItemDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMultipleCovarCategoriesResponseItemData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...CovarCategoryFromJSONTyped(json, true), ...UpdateCovarCategoryRequestFromJSONTyped(json, true) };
}

export function UpdateMultipleCovarCategoriesResponseItemDataToJSON(value?: UpdateMultipleCovarCategoriesResponseItemData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfCovarCategory(value)) {
        return CovarCategoryToJSON(value as CovarCategory);
    }
    if (instanceOfUpdateCovarCategoryRequest(value)) {
        return UpdateCovarCategoryRequestToJSON(value as UpdateCovarCategoryRequest);
    }

    return {};
}

