/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AnalysisUnitVersion } from './AnalysisUnitVersion';
import {
    AnalysisUnitVersionFromJSON,
    AnalysisUnitVersionFromJSONTyped,
    AnalysisUnitVersionToJSON,
} from './AnalysisUnitVersion';

/**
 * Update analysis unit version response object.
 * @export
 * @interface UpdateAnalysisUnitVersionResponse
 */
export interface UpdateAnalysisUnitVersionResponse {
    /**
     * 
     * @type {AnalysisUnitVersion}
     * @memberof UpdateAnalysisUnitVersionResponse
     */
    data: AnalysisUnitVersion;
    /**
     * 
     * @type {string}
     * @memberof UpdateAnalysisUnitVersionResponse
     */
    message: string;
}

/**
 * Check if a given object implements the UpdateAnalysisUnitVersionResponse interface.
 */
export function instanceOfUpdateAnalysisUnitVersionResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function UpdateAnalysisUnitVersionResponseFromJSON(json: any): UpdateAnalysisUnitVersionResponse {
    return UpdateAnalysisUnitVersionResponseFromJSONTyped(json, false);
}

export function UpdateAnalysisUnitVersionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAnalysisUnitVersionResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': AnalysisUnitVersionFromJSON(json['data']),
        'message': json['message'],
    };
}

export function UpdateAnalysisUnitVersionResponseToJSON(value?: UpdateAnalysisUnitVersionResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': AnalysisUnitVersionToJSON(value.data),
        'message': value.message,
    };
}

