/* tslint:disable */
/* eslint-disable */
/**
 * count-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EntryColumnMappingVersion } from './EntryColumnMappingVersion';
import {
    EntryColumnMappingVersionFromJSON,
    EntryColumnMappingVersionFromJSONTyped,
    EntryColumnMappingVersionToJSON,
} from './EntryColumnMappingVersion';

/**
 * Update entry column mapping response object.
 * @export
 * @interface UpdateEntryColumnMappingVersionResponse
 */
export interface UpdateEntryColumnMappingVersionResponse {
    /**
     * 
     * @type {EntryColumnMappingVersion}
     * @memberof UpdateEntryColumnMappingVersionResponse
     */
    data: EntryColumnMappingVersion;
    /**
     * 
     * @type {string}
     * @memberof UpdateEntryColumnMappingVersionResponse
     */
    message: string;
}

/**
 * Check if a given object implements the UpdateEntryColumnMappingVersionResponse interface.
 */
export function instanceOfUpdateEntryColumnMappingVersionResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function UpdateEntryColumnMappingVersionResponseFromJSON(json: any): UpdateEntryColumnMappingVersionResponse {
    return UpdateEntryColumnMappingVersionResponseFromJSONTyped(json, false);
}

export function UpdateEntryColumnMappingVersionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateEntryColumnMappingVersionResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': EntryColumnMappingVersionFromJSON(json['data']),
        'message': json['message'],
    };
}

export function UpdateEntryColumnMappingVersionResponseToJSON(value?: UpdateEntryColumnMappingVersionResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': EntryColumnMappingVersionToJSON(value.data),
        'message': value.message,
    };
}

