/* tslint:disable */
/* eslint-disable */
/**
 * imperia-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * Attaching media
 * @export
 * @interface AttachingMedia
 */
export interface AttachingMedia {
  /**
   *
   * @type {number}
   * @memberof AttachingMedia
   */
  id: number;
}

/**
 * Check if a given object implements the AttachingMedia interface.
 */
export function instanceOfAttachingMedia(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "id" in value;

  return isInstance;
}

export function AttachingMediaFromJSON(json: any): AttachingMedia {
  return AttachingMediaFromJSONTyped(json, false);
}

export function AttachingMediaFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AttachingMedia {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
  };
}

export function AttachingMediaToJSON(value?: AttachingMedia | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
  };
}
