/* tslint:disable */
/* eslint-disable */
/**
 * imperia-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
} from './PaginationMeta';
import type { RestaurantReview } from './RestaurantReview';
import {
    RestaurantReviewFromJSON,
    RestaurantReviewFromJSONTyped,
    RestaurantReviewToJSON,
} from './RestaurantReview';

/**
 * Index restaurant reviews response object.
 * @export
 * @interface IndexRestaurantReviewResponse
 */
export interface IndexRestaurantReviewResponse {
    /**
     * 
     * @type {Array<RestaurantReview>}
     * @memberof IndexRestaurantReviewResponse
     */
    data: Array<RestaurantReview>;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof IndexRestaurantReviewResponse
     */
    meta: PaginationMeta;
    /**
     * 
     * @type {string}
     * @memberof IndexRestaurantReviewResponse
     */
    message: string;
}

/**
 * Check if a given object implements the IndexRestaurantReviewResponse interface.
 */
export function instanceOfIndexRestaurantReviewResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "meta" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function IndexRestaurantReviewResponseFromJSON(json: any): IndexRestaurantReviewResponse {
    return IndexRestaurantReviewResponseFromJSONTyped(json, false);
}

export function IndexRestaurantReviewResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndexRestaurantReviewResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(RestaurantReviewFromJSON)),
        'meta': PaginationMetaFromJSON(json['meta']),
        'message': json['message'],
    };
}

export function IndexRestaurantReviewResponseToJSON(value?: IndexRestaurantReviewResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(RestaurantReviewToJSON)),
        'meta': PaginationMetaToJSON(value.meta),
        'message': value.message,
    };
}

