/* tslint:disable */
/* eslint-disable */
/**
 * imperia-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Discount } from './Discount';
import {
    DiscountFromJSON,
    DiscountFromJSONTyped,
    DiscountToJSON,
} from './Discount';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
} from './PaginationMeta';

/**
 * Index discounts response object.
 * @export
 * @interface IndexDiscountResponse
 */
export interface IndexDiscountResponse {
    /**
     * 
     * @type {Array<Discount>}
     * @memberof IndexDiscountResponse
     */
    data: Array<Discount>;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof IndexDiscountResponse
     */
    meta: PaginationMeta;
    /**
     * 
     * @type {string}
     * @memberof IndexDiscountResponse
     */
    message: string;
}

/**
 * Check if a given object implements the IndexDiscountResponse interface.
 */
export function instanceOfIndexDiscountResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "meta" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function IndexDiscountResponseFromJSON(json: any): IndexDiscountResponse {
    return IndexDiscountResponseFromJSONTyped(json, false);
}

export function IndexDiscountResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndexDiscountResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(DiscountFromJSON)),
        'meta': PaginationMetaFromJSON(json['meta']),
        'message': json['message'],
    };
}

export function IndexDiscountResponseToJSON(value?: IndexDiscountResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(DiscountToJSON)),
        'meta': PaginationMetaToJSON(value.meta),
        'message': value.message,
    };
}

