/* tslint:disable */
/* eslint-disable */
/**
 * imperia-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { PaginationMeta } from "./PaginationMeta";
import {
  PaginationMetaFromJSON,
  PaginationMetaFromJSONTyped,
  PaginationMetaToJSON,
} from "./PaginationMeta";
import type { SpaceReservation } from "./SpaceReservation";
import {
  SpaceReservationFromJSON,
  SpaceReservationFromJSONTyped,
  SpaceReservationToJSON,
} from "./SpaceReservation";

/**
 * Index spaces reservations response object.
 * @export
 * @interface IndexSpaceReservationsResponse
 */
export interface IndexSpaceReservationsResponse {
  /**
   *
   * @type {Array<SpaceReservation>}
   * @memberof IndexSpaceReservationsResponse
   */
  data: Array<SpaceReservation>;
  /**
   *
   * @type {PaginationMeta}
   * @memberof IndexSpaceReservationsResponse
   */
  meta: PaginationMeta;
  /**
   *
   * @type {string}
   * @memberof IndexSpaceReservationsResponse
   */
  message: string;
}

/**
 * Check if a given object implements the IndexSpaceReservationsResponse interface.
 */
export function instanceOfIndexSpaceReservationsResponse(
  value: object
): boolean {
  let isInstance = true;
  isInstance = isInstance && "data" in value;
  isInstance = isInstance && "meta" in value;
  isInstance = isInstance && "message" in value;

  return isInstance;
}

export function IndexSpaceReservationsResponseFromJSON(
  json: any
): IndexSpaceReservationsResponse {
  return IndexSpaceReservationsResponseFromJSONTyped(json, false);
}

export function IndexSpaceReservationsResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): IndexSpaceReservationsResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: (json["data"] as Array<any>).map(SpaceReservationFromJSON),
    meta: PaginationMetaFromJSON(json["meta"]),
    message: json["message"],
  };
}

export function IndexSpaceReservationsResponseToJSON(
  value?: IndexSpaceReservationsResponse | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: (value.data as Array<any>).map(SpaceReservationToJSON),
    meta: PaginationMetaToJSON(value.meta),
    message: value.message,
  };
}
