/* tslint:disable */
/* eslint-disable */
/**
 * imperia-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * Supports login by credantials (`email` and `password`) and
 *     by remember token (`remember_token`).
 * @export
 * @interface LoginRequest
 */
export interface LoginRequest {
  /**
   * By credentials. Required with `password`
   * @type {string}
   * @memberof LoginRequest
   */
  email?: string;
  /**
   * By credentials. Required with `email`
   * @type {string}
   * @memberof LoginRequest
   */
  password?: string;
  /**
   * By remember token
   * @type {string}
   * @memberof LoginRequest
   */
  rememberToken?: string;
}

/**
 * Check if a given object implements the LoginRequest interface.
 */
export function instanceOfLoginRequest(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function LoginRequestFromJSON(json: any): LoginRequest {
  return LoginRequestFromJSONTyped(json, false);
}

export function LoginRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): LoginRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    email: !exists(json, "email") ? undefined : json["email"],
    password: !exists(json, "password") ? undefined : json["password"],
    rememberToken: !exists(json, "remember_token")
      ? undefined
      : json["remember_token"],
  };
}

export function LoginRequestToJSON(value?: LoginRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    email: value.email,
    password: value.password,
    remember_token: value.rememberToken,
  };
}
