/* tslint:disable */
/* eslint-disable */
/**
 * imperia-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * Generate url for accessing order's invoice request
 * @export
 * @interface OrderInvoiceUrlRequest
 */
export interface OrderInvoiceUrlRequest {
  /**
   *
   * @type {string}
   * @memberof OrderInvoiceUrlRequest
   */
  endpoint?: OrderInvoiceUrlRequestEndpointEnum;
}

/**
 * @export
 */
export const OrderInvoiceUrlRequestEndpointEnum = {
  Pdf: "pdf",
  View: "view",
} as const;
export type OrderInvoiceUrlRequestEndpointEnum =
  (typeof OrderInvoiceUrlRequestEndpointEnum)[keyof typeof OrderInvoiceUrlRequestEndpointEnum];

/**
 * Check if a given object implements the OrderInvoiceUrlRequest interface.
 */
export function instanceOfOrderInvoiceUrlRequest(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function OrderInvoiceUrlRequestFromJSON(
  json: any
): OrderInvoiceUrlRequest {
  return OrderInvoiceUrlRequestFromJSONTyped(json, false);
}

export function OrderInvoiceUrlRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): OrderInvoiceUrlRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    endpoint: !exists(json, "endpoint") ? undefined : json["endpoint"],
  };
}

export function OrderInvoiceUrlRequestToJSON(
  value?: OrderInvoiceUrlRequest | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    endpoint: value.endpoint,
  };
}
