/* tslint:disable */
/* eslint-disable */
/**
 * imperia-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * Schedule object for update restaurant request.
 * @export
 * @interface ScheduleForUpdateRestaurantRequest
 */
export interface ScheduleForUpdateRestaurantRequest {
  /**
   *
   * @type {number}
   * @memberof ScheduleForUpdateRestaurantRequest
   */
  id?: number;
  /**
   *
   * @type {number}
   * @memberof ScheduleForUpdateRestaurantRequest
   */
  restaurantId?: number;
  /**
   *
   * @type {string}
   * @memberof ScheduleForUpdateRestaurantRequest
   */
  weekday: ScheduleForUpdateRestaurantRequestWeekdayEnum;
  /**
   *
   * @type {number}
   * @memberof ScheduleForUpdateRestaurantRequest
   */
  begHour: number;
  /**
   *
   * @type {number}
   * @memberof ScheduleForUpdateRestaurantRequest
   */
  begMinute: number;
  /**
   *
   * @type {number}
   * @memberof ScheduleForUpdateRestaurantRequest
   */
  endHour: number;
  /**
   *
   * @type {number}
   * @memberof ScheduleForUpdateRestaurantRequest
   */
  endMinute: number;
  /**
   *
   * @type {boolean}
   * @memberof ScheduleForUpdateRestaurantRequest
   */
  archived?: boolean;
}

/**
 * @export
 */
export const ScheduleForUpdateRestaurantRequestWeekdayEnum = {
  Monday: "monday",
  Tuesday: "tuesday",
  Wednesday: "wednesday",
  Thursday: "thursday",
  Friday: "friday",
  Saturday: "saturday",
  Sunday: "sunday",
} as const;
export type ScheduleForUpdateRestaurantRequestWeekdayEnum =
  (typeof ScheduleForUpdateRestaurantRequestWeekdayEnum)[keyof typeof ScheduleForUpdateRestaurantRequestWeekdayEnum];

/**
 * Check if a given object implements the ScheduleForUpdateRestaurantRequest interface.
 */
export function instanceOfScheduleForUpdateRestaurantRequest(
  value: object
): boolean {
  let isInstance = true;
  isInstance = isInstance && "weekday" in value;
  isInstance = isInstance && "begHour" in value;
  isInstance = isInstance && "begMinute" in value;
  isInstance = isInstance && "endHour" in value;
  isInstance = isInstance && "endMinute" in value;

  return isInstance;
}

export function ScheduleForUpdateRestaurantRequestFromJSON(
  json: any
): ScheduleForUpdateRestaurantRequest {
  return ScheduleForUpdateRestaurantRequestFromJSONTyped(json, false);
}

export function ScheduleForUpdateRestaurantRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ScheduleForUpdateRestaurantRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    restaurantId: !exists(json, "restaurant_id")
      ? undefined
      : json["restaurant_id"],
    weekday: json["weekday"],
    begHour: json["beg_hour"],
    begMinute: json["beg_minute"],
    endHour: json["end_hour"],
    endMinute: json["end_minute"],
    archived: !exists(json, "archived") ? undefined : json["archived"],
  };
}

export function ScheduleForUpdateRestaurantRequestToJSON(
  value?: ScheduleForUpdateRestaurantRequest | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    restaurant_id: value.restaurantId,
    weekday: value.weekday,
    beg_hour: value.begHour,
    beg_minute: value.begMinute,
    end_hour: value.endHour,
    end_minute: value.endMinute,
    archived: value.archived,
  };
}
