/* tslint:disable */
/* eslint-disable */
/**
 * imperia-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Customer } from './Customer';
import {
    CustomerFromJSON,
    CustomerFromJSONTyped,
    CustomerToJSON,
} from './Customer';

/**
 * Show customer response object.
 * @export
 * @interface ShowCustomerResponse
 */
export interface ShowCustomerResponse {
    /**
     * 
     * @type {Customer}
     * @memberof ShowCustomerResponse
     */
    data: Customer;
    /**
     * 
     * @type {string}
     * @memberof ShowCustomerResponse
     */
    message: string;
}

/**
 * Check if a given object implements the ShowCustomerResponse interface.
 */
export function instanceOfShowCustomerResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function ShowCustomerResponseFromJSON(json: any): ShowCustomerResponse {
    return ShowCustomerResponseFromJSONTyped(json, false);
}

export function ShowCustomerResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShowCustomerResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': CustomerFromJSON(json['data']),
        'message': json['message'],
    };
}

export function ShowCustomerResponseToJSON(value?: ShowCustomerResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': CustomerToJSON(value.data),
        'message': value.message,
    };
}

