/* tslint:disable */
/* eslint-disable */
/**
 * imperia-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Notification } from './Notification';
import {
    NotificationFromJSON,
    NotificationFromJSONTyped,
    NotificationToJSON,
} from './Notification';

/**
 * Show notification response object.
 * @export
 * @interface ShowNotificationResponse
 */
export interface ShowNotificationResponse {
    /**
     * 
     * @type {Notification}
     * @memberof ShowNotificationResponse
     */
    data: Notification;
    /**
     * 
     * @type {string}
     * @memberof ShowNotificationResponse
     */
    message: string;
}

/**
 * Check if a given object implements the ShowNotificationResponse interface.
 */
export function instanceOfShowNotificationResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function ShowNotificationResponseFromJSON(json: any): ShowNotificationResponse {
    return ShowNotificationResponseFromJSONTyped(json, false);
}

export function ShowNotificationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShowNotificationResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': NotificationFromJSON(json['data']),
        'message': json['message'],
    };
}

export function ShowNotificationResponseToJSON(value?: ShowNotificationResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': NotificationToJSON(value.data),
        'message': value.message,
    };
}

