/* tslint:disable */
/* eslint-disable */
/**
 * imperia-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { Restaurant } from "./Restaurant";
import {
  RestaurantFromJSON,
  RestaurantFromJSONTyped,
  RestaurantToJSON,
} from "./Restaurant";

/**
 * Store restaurant response object.
 * @export
 * @interface StoreRestaurantResponse
 */
export interface StoreRestaurantResponse {
  /**
   *
   * @type {Restaurant}
   * @memberof StoreRestaurantResponse
   */
  data: Restaurant;
  /**
   *
   * @type {string}
   * @memberof StoreRestaurantResponse
   */
  message: string;
}

/**
 * Check if a given object implements the StoreRestaurantResponse interface.
 */
export function instanceOfStoreRestaurantResponse(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "data" in value;
  isInstance = isInstance && "message" in value;

  return isInstance;
}

export function StoreRestaurantResponseFromJSON(
  json: any
): StoreRestaurantResponse {
  return StoreRestaurantResponseFromJSONTyped(json, false);
}

export function StoreRestaurantResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): StoreRestaurantResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: RestaurantFromJSON(json["data"]),
    message: json["message"],
  };
}

export function StoreRestaurantResponseToJSON(
  value?: StoreRestaurantResponse | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: RestaurantToJSON(value.data),
    message: value.message,
  };
}
