/* tslint:disable */
/* eslint-disable */
/**
 * imperia-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * Update user response object.
 * @export
 * @interface UpdateUserResponse
 */
export interface UpdateUserResponse {
    /**
     * 
     * @type {User}
     * @memberof UpdateUserResponse
     */
    data: User;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserResponse
     */
    message: string;
}

/**
 * Check if a given object implements the UpdateUserResponse interface.
 */
export function instanceOfUpdateUserResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function UpdateUserResponseFromJSON(json: any): UpdateUserResponse {
    return UpdateUserResponseFromJSONTyped(json, false);
}

export function UpdateUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': UserFromJSON(json['data']),
        'message': json['message'],
    };
}

export function UpdateUserResponseToJSON(value?: UpdateUserResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': UserToJSON(value.data),
        'message': value.message,
    };
}

