/* tslint:disable */
/* eslint-disable */
/**
 * imperia-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * Update restaurant request
 * @export
 * @interface UpdateRestaurantRequest
 */
export interface UpdateRestaurantRequest {
  /**
   * Must be unique within the database.
   * @type {string}
   * @memberof UpdateRestaurantRequest
   */
  slug?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateRestaurantRequest
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateRestaurantRequest
   */
  country?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateRestaurantRequest
   */
  city?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateRestaurantRequest
   */
  place?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateRestaurantRequest
   */
  timezone?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateRestaurantRequest
   */
  email?: string;
  /**
   * Phone number may start with a plus and must contain only digits 0-9.
   * @type {string}
   * @memberof UpdateRestaurantRequest
   */
  phone?: string;
  /**
   * Link to restaurant's location on Google Maps.
   * @type {string}
   * @memberof UpdateRestaurantRequest
   */
  location?: string | null;
  /**
   * Link to restaurant's website.
   * @type {string}
   * @memberof UpdateRestaurantRequest
   */
  website?: string | null;
}

/**
 * Check if a given object implements the UpdateRestaurantRequest interface.
 */
export function instanceOfUpdateRestaurantRequest(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function UpdateRestaurantRequestFromJSON(
  json: any
): UpdateRestaurantRequest {
  return UpdateRestaurantRequestFromJSONTyped(json, false);
}

export function UpdateRestaurantRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UpdateRestaurantRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    slug: !exists(json, "slug") ? undefined : json["slug"],
    name: !exists(json, "name") ? undefined : json["name"],
    country: !exists(json, "country") ? undefined : json["country"],
    city: !exists(json, "city") ? undefined : json["city"],
    place: !exists(json, "place") ? undefined : json["place"],
    timezone: !exists(json, "timezone") ? undefined : json["timezone"],
    email: !exists(json, "email") ? undefined : json["email"],
    phone: !exists(json, "phone") ? undefined : json["phone"],
    location: !exists(json, "location") ? undefined : json["location"],
    website: !exists(json, "website") ? undefined : json["website"],
  };
}

export function UpdateRestaurantRequestToJSON(
  value?: UpdateRestaurantRequest | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    slug: value.slug,
    name: value.name,
    country: value.country,
    city: value.city,
    place: value.place,
    timezone: value.timezone,
    email: value.email,
    phone: value.phone,
    location: value.location,
    website: value.website,
  };
}
