/* tslint:disable */
/* eslint-disable */
/**
 * imperia-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { Media } from "./Media";
import { MediaFromJSON, MediaFromJSONTyped, MediaToJSON } from "./Media";

/**
 * Update media response object.
 * @export
 * @interface UpdateMediaResponse
 */
export interface UpdateMediaResponse {
  /**
   *
   * @type {Media}
   * @memberof UpdateMediaResponse
   */
  data: Media;
  /**
   *
   * @type {string}
   * @memberof UpdateMediaResponse
   */
  message: string;
}

/**
 * Check if a given object implements the UpdateMediaResponse interface.
 */
export function instanceOfUpdateMediaResponse(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "data" in value;
  isInstance = isInstance && "message" in value;

  return isInstance;
}

export function UpdateMediaResponseFromJSON(json: any): UpdateMediaResponse {
  return UpdateMediaResponseFromJSONTyped(json, false);
}

export function UpdateMediaResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UpdateMediaResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: MediaFromJSON(json["data"]),
    message: json["message"],
  };
}

export function UpdateMediaResponseToJSON(
  value?: UpdateMediaResponse | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: MediaToJSON(value.data),
    message: value.message,
  };
}
