/* tslint:disable */
/* eslint-disable */
/**
 * imperia-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { Comment } from "./Comment";
import {
  CommentFromJSON,
  CommentFromJSONTyped,
  CommentToJSON,
} from "./Comment";

/**
 * Update comment response object.
 * @export
 * @interface UpdateCommentResponse
 */
export interface UpdateCommentResponse {
  /**
   *
   * @type {Comment}
   * @memberof UpdateCommentResponse
   */
  data: Comment;
  /**
   *
   * @type {string}
   * @memberof UpdateCommentResponse
   */
  message: string;
}

/**
 * Check if a given object implements the UpdateCommentResponse interface.
 */
export function instanceOfUpdateCommentResponse(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "data" in value;
  isInstance = isInstance && "message" in value;

  return isInstance;
}

export function UpdateCommentResponseFromJSON(
  json: any
): UpdateCommentResponse {
  return UpdateCommentResponseFromJSONTyped(json, false);
}

export function UpdateCommentResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UpdateCommentResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: CommentFromJSON(json["data"]),
    message: json["message"],
  };
}

export function UpdateCommentResponseToJSON(
  value?: UpdateCommentResponse | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: CommentToJSON(value.data),
    message: value.message,
  };
}
